package scapecraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelKKspawn extends ModelBase
{
	//fields
	ModelRenderer mouth;
	ModelRenderer l_pincer;
	ModelRenderer r_pincer;
	ModelRenderer l_mid_pincer;
	ModelRenderer r_mid_pincer;
	ModelRenderer l_end_pincer;
	ModelRenderer r_end_pincer;
	ModelRenderer head_top;
	ModelRenderer neck;
	ModelRenderer head;
	ModelRenderer main_body;
	ModelRenderer top_body;
	ModelRenderer back_body;
	ModelRenderer l_leg_top;
	ModelRenderer r_leg_top;
	ModelRenderer l_leg_mid;
	ModelRenderer r_leg_mid;
	ModelRenderer l_leg_bottom;
	ModelRenderer r_leg_bottom;
	ModelRenderer l_mid_leg_top;
	ModelRenderer r_mid_leg_top;
	ModelRenderer l_mid_leg_bottom;
	ModelRenderer r_mid_leg_bottom;
	ModelRenderer l_back_leg_top;
	ModelRenderer r_back_leg_top;
	ModelRenderer l_back_leg_bottom;
	ModelRenderer r_back_leg_bottom;
	ModelRenderer front_leg_joint;
	ModelRenderer top_head_curve;
	ModelRenderer mid_leg_joint;
	ModelRenderer back_leg_joint;
	ModelRenderer head_piece_top;
	ModelRenderer antanae_l;
	ModelRenderer antenae_r;

	public ModelKKspawn()
	{
		textureWidth = 256;
		textureHeight = 64;

		mouth = new ModelRenderer(this, 42, 18);
		mouth.addBox(2F, 0F, 0F, 4, 5, 5);
		mouth.setRotationPoint(-1F, -3F, 0F);
		mouth.setTextureSize(256, 64);
		mouth.mirror = true;
		setRotation(mouth, -0.3490659F, 0F, 0F);
		l_pincer = new ModelRenderer(this, 50, 46);
		l_pincer.addBox(0F, 0F, 0F, 2, 1, 6);
		l_pincer.setRotationPoint(-3F, 0F, -2F);
		l_pincer.setTextureSize(256, 64);
		l_pincer.mirror = true;
		setRotation(l_pincer, 0.3490659F, 0.3490659F, 0F);
		r_pincer = new ModelRenderer(this, 50, 56);
		r_pincer.addBox(0F, 0F, 0F, 2, 1, 6);
		r_pincer.setRotationPoint(7F, 0F, -3F);
		r_pincer.setTextureSize(256, 64);
		r_pincer.mirror = true;
		setRotation(r_pincer, 0.3490659F, -0.3490659F, 0F);
		l_mid_pincer = new ModelRenderer(this, 68, 41);
		l_mid_pincer.addBox(0F, -0.5F, 0F, 2, 1, 4);
		l_mid_pincer.setRotationPoint(-2.8F, 1.7F, -5.7F);
		l_mid_pincer.setTextureSize(256, 64);
		l_mid_pincer.mirror = true;
		setRotation(l_mid_pincer, 0.3490659F, 0F, 0F);
		r_mid_pincer = new ModelRenderer(this, 68, 57);
		r_mid_pincer.addBox(0F, 0F, 0F, 2, 1, 4);
		r_mid_pincer.setRotationPoint(6.7F, 0.9F, -6F);
		r_mid_pincer.setTextureSize(256, 64);
		r_mid_pincer.mirror = true;
		setRotation(r_mid_pincer, 0.3490659F, 0F, 0F);
		l_end_pincer = new ModelRenderer(this, 83, 48);
		l_end_pincer.addBox(0F, 0F, 0F, 2, 1, 4);
		l_end_pincer.setRotationPoint(-1.7F, 2.55F, -8.533334F);
		l_end_pincer.setTextureSize(256, 64);
		l_end_pincer.mirror = true;
		setRotation(l_end_pincer, 0.3490659F, -0.2617994F, -0.0174533F);
		r_end_pincer = new ModelRenderer(this, 83, 58);
		r_end_pincer.addBox(0F, 0F, 0F, 2, 1, 4);
		r_end_pincer.setRotationPoint(5.7F, 2F, -8F);
		r_end_pincer.setTextureSize(256, 64);
		r_end_pincer.mirror = true;
		setRotation(r_end_pincer, 0.3490659F, 0.2617994F, 0.0174533F);
		head_top = new ModelRenderer(this, 228, 0);
		head_top.addBox(0F, 0F, 0F, 6, 9, 1);
		head_top.setRotationPoint(0F, -13F, 8F);
		head_top.setTextureSize(256, 64);
		head_top.mirror = true;
		setRotation(head_top, -0.3490659F, 0F, 0F);
		neck = new ModelRenderer(this, 1, 0);
		neck.addBox(0F, 0F, 0F, 4, 2, 9);
		neck.setRotationPoint(1F, -1F, 4F);
		neck.setTextureSize(256, 64);
		neck.mirror = true;
		setRotation(neck, 0F, 0F, 0F);
		head = new ModelRenderer(this, 39, 0);
		head.addBox(0F, 0F, 0F, 6, 5, 5);
		head.setRotationPoint(0F, -6F, 0F);
		head.setTextureSize(256, 64);
		head.mirror = true;
		setRotation(head, -0.1047198F, 0F, 0F);
		main_body = new ModelRenderer(this, 62, 0);
		main_body.addBox(0F, 0F, 0F, 12, 10, 20);
		main_body.setRotationPoint(-3F, -8F, 7F);
		main_body.setTextureSize(256, 64);
		main_body.mirror = true;
		setRotation(main_body, 0F, 0F, 0F);
		top_body = new ModelRenderer(this, 127, 0);
		top_body.addBox(0F, 0F, 0F, 10, 2, 20);
		top_body.setRotationPoint(-2F, -10F, 7F);
		top_body.setTextureSize(256, 64);
		top_body.mirror = true;
		setRotation(top_body, 0F, 0F, 0F);
		back_body = new ModelRenderer(this, 188, 0);
		back_body.addBox(0F, 0F, 0F, 12, 10, 7);
		back_body.setRotationPoint(-3F, -5F, 22F);
		back_body.setTextureSize(256, 64);
		back_body.mirror = true;
		setRotation(back_body, 0.6457718F, 0F, 0F);
		l_leg_top = new ModelRenderer(this, 0, 13);
		l_leg_top.addBox(0F, 0F, 0F, 2, 5, 2);
		l_leg_top.setRotationPoint(-5F, 0F, 7F);
		l_leg_top.setTextureSize(256, 64);
		l_leg_top.mirror = true;
		setRotation(l_leg_top, -0.5235988F, 0F, 0.5235988F);
		r_leg_top = new ModelRenderer(this, 0, 23);
		r_leg_top.addBox(0F, 0F, 0F, 2, 5, 2);
		r_leg_top.setRotationPoint(9F, 1F, 7F);
		r_leg_top.setTextureSize(256, 64);
		r_leg_top.mirror = true;
		setRotation(r_leg_top, -0.5235988F, 0F, -0.5235988F);
		l_leg_mid = new ModelRenderer(this, 0, 34);
		l_leg_mid.addBox(0F, 0F, 0F, 5, 2, 2);
		l_leg_mid.setRotationPoint(-10F, 4F, 4F);
		l_leg_mid.setTextureSize(256, 64);
		l_leg_mid.mirror = true;
		setRotation(l_leg_mid, 0F, 0F, 0F);
		r_leg_mid = new ModelRenderer(this, 0, 40);
		r_leg_mid.addBox(0F, 0F, 0F, 5, 2, 2);
		r_leg_mid.setRotationPoint(11F, 4F, 4F);
		r_leg_mid.setTextureSize(256, 64);
		r_leg_mid.mirror = true;
		setRotation(r_leg_mid, 0F, 0F, 0F);
		l_leg_bottom = new ModelRenderer(this, 150, 42);
		l_leg_bottom.addBox(0F, 0F, 0F, 2, 7, 2);
		l_leg_bottom.setRotationPoint(-10F, 6F, 4F);
		l_leg_bottom.setTextureSize(256, 64);
		l_leg_bottom.mirror = true;
		setRotation(l_leg_bottom, 0F, -0.3490659F, 0F);
		r_leg_bottom = new ModelRenderer(this, 160, 42);
		r_leg_bottom.addBox(0F, 0F, 0F, 2, 7, 2);
		r_leg_bottom.setRotationPoint(14F, 6F, 4F);
		r_leg_bottom.setTextureSize(256, 64);
		r_leg_bottom.mirror = true;
		setRotation(r_leg_bottom, 0F, 0.3490659F, 0F);
		l_mid_leg_top = new ModelRenderer(this, 11, 13);
		l_mid_leg_top.addBox(0F, 0F, 0F, 2, 7, 2);
		l_mid_leg_top.setRotationPoint(-3F, 0F, 15F);
		l_mid_leg_top.setTextureSize(256, 64);
		l_mid_leg_top.mirror = true;
		setRotation(l_mid_leg_top, 0F, 0F, 0.8726646F);
		r_mid_leg_top = new ModelRenderer(this, 12, 23);
		r_mid_leg_top.addBox(0F, 0F, 0F, 2, 7, 2);
		r_mid_leg_top.setRotationPoint(8F, 1F, 15F);
		r_mid_leg_top.setTextureSize(256, 64);
		r_mid_leg_top.mirror = true;
		setRotation(r_mid_leg_top, 0F, 0F, -0.8726646F);
		l_mid_leg_bottom = new ModelRenderer(this, 180, 52);
		l_mid_leg_bottom.addBox(0F, 0F, 0F, 2, 9, 2);
		l_mid_leg_bottom.setRotationPoint(-9F, 4F, 15F);
		l_mid_leg_bottom.setTextureSize(256, 64);
		l_mid_leg_bottom.mirror = true;
		setRotation(l_mid_leg_bottom, 0F, 0F, 0F);
		r_mid_leg_bottom = new ModelRenderer(this, 160, 52);
		r_mid_leg_bottom.addBox(0F, 0F, 0F, 2, 9, 2);
		r_mid_leg_bottom.setRotationPoint(13F, 4F, 15F);
		r_mid_leg_bottom.setTextureSize(256, 64);
		r_mid_leg_bottom.mirror = true;
		setRotation(r_mid_leg_bottom, 0F, 0F, 0F);
		l_back_leg_top = new ModelRenderer(this, 22, 13);
		l_back_leg_top.addBox(0F, 0F, 0F, 2, 7, 2);
		l_back_leg_top.setRotationPoint(-3F, 0F, 23F);
		l_back_leg_top.setTextureSize(256, 64);
		l_back_leg_top.mirror = true;
		setRotation(l_back_leg_top, 0.2617994F, 0F, 0.8726646F);
		r_back_leg_top = new ModelRenderer(this, 22, 23);
		r_back_leg_top.addBox(0F, 0F, 0F, 2, 7, 2);
		r_back_leg_top.setRotationPoint(8F, 1F, 23F);
		r_back_leg_top.setTextureSize(256, 64);
		r_back_leg_top.mirror = true;
		setRotation(r_back_leg_top, 0.2617994F, 0F, -0.8726646F);
		l_back_leg_bottom = new ModelRenderer(this, 170, 52);
		l_back_leg_bottom.addBox(0F, 0F, 0F, 2, 9, 2);
		l_back_leg_bottom.setRotationPoint(-8F, 4F, 25F);
		l_back_leg_bottom.setTextureSize(256, 64);
		l_back_leg_bottom.mirror = true;
		setRotation(l_back_leg_bottom, 0F, 0.2617994F, 0F);
		r_back_leg_bottom = new ModelRenderer(this, 150, 52);
		r_back_leg_bottom.addBox(0F, 0F, 0F, 2, 9, 2);
		r_back_leg_bottom.setRotationPoint(13F, 4F, 24.5F);
		r_back_leg_bottom.setTextureSize(256, 64);
		r_back_leg_bottom.mirror = true;
		setRotation(r_back_leg_bottom, 0F, -0.4363323F, 0F);
		front_leg_joint = new ModelRenderer(this, 188, 19);
		front_leg_joint.addBox(0F, 0F, 0F, 16, 4, 5);
		front_leg_joint.setRotationPoint(-5F, 0F, 5F);
		front_leg_joint.setTextureSize(256, 64);
		front_leg_joint.mirror = true;
		setRotation(front_leg_joint, 0F, 0F, 0F);
		top_head_curve = new ModelRenderer(this, 50, 11);
		top_head_curve.addBox(0F, 0F, 0F, 4, 5, 1);
		top_head_curve.setRotationPoint(1F, -9F, 7F);
		top_head_curve.setTextureSize(256, 64);
		top_head_curve.mirror = true;
		setRotation(top_head_curve, -0.8726646F, 0F, 0F);
		mid_leg_joint = new ModelRenderer(this, 188, 29);
		mid_leg_joint.addBox(0F, 0F, 0F, 16, 5, 5);
		mid_leg_joint.setRotationPoint(-5F, -1F, 13.5F);
		mid_leg_joint.setTextureSize(256, 64);
		mid_leg_joint.mirror = true;
		setRotation(mid_leg_joint, 0F, 0F, 0F);
		back_leg_joint = new ModelRenderer(this, 188, 40);
		back_leg_joint.addBox(0F, 0F, 0F, 16, 5, 5);
		back_leg_joint.setRotationPoint(-5F, -1F, 22F);
		back_leg_joint.setTextureSize(256, 64);
		back_leg_joint.mirror = true;
		setRotation(back_leg_joint, 0F, 0F, 0F);
		head_piece_top = new ModelRenderer(this, 141, 24);
		head_piece_top.addBox(0F, 0F, 0F, 12, 10, 1);
		head_piece_top.setRotationPoint(-3F, -16F, 15F);
		head_piece_top.setTextureSize(256, 64);
		head_piece_top.mirror = true;
		setRotation(head_piece_top, -0.2617994F, -0.0872665F, 0F);
		antanae_l = new ModelRenderer(this, 0, 1);
		antanae_l.addBox(0F, 0F, 0F, 1, 6, 1);
		antanae_l.setRotationPoint(-2F, -10F, 0F);
		antanae_l.setTextureSize(256, 64);
		antanae_l.mirror = true;
		setRotation(antanae_l, 0F, 0F, -0.4363323F);
		antenae_r = new ModelRenderer(this, 0, 0);
		antenae_r.addBox(0F, 0F, 0F, 1, 6, 1);
		antenae_r.setRotationPoint(7F, -11F, 0F);
		antenae_r.setTextureSize(256, 64);
		antenae_r.mirror = true;
		setRotation(antenae_r, 0F, 0F, 0.4363323F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		mouth.render(f5);
		l_pincer.render(f5);
		r_pincer.render(f5);
		l_mid_pincer.render(f5);
		r_mid_pincer.render(f5);
		l_end_pincer.render(f5);
		r_end_pincer.render(f5);
		head_top.render(f5);
		neck.render(f5);
		head.render(f5);
		main_body.render(f5);
		top_body.render(f5);
		back_body.render(f5);
		l_leg_top.render(f5);
		r_leg_top.render(f5);
		l_leg_mid.render(f5);
		r_leg_mid.render(f5);
		l_leg_bottom.render(f5);
		r_leg_bottom.render(f5);
		l_mid_leg_top.render(f5);
		r_mid_leg_top.render(f5);
		l_mid_leg_bottom.render(f5);
		r_mid_leg_bottom.render(f5);
		l_back_leg_top.render(f5);
		r_back_leg_top.render(f5);
		l_back_leg_bottom.render(f5);
		r_back_leg_bottom.render(f5);
		front_leg_joint.render(f5);
		top_head_curve.render(f5);
		mid_leg_joint.render(f5);
		back_leg_joint.render(f5);
		head_piece_top.render(f5);
		antanae_l.render(f5);
		antenae_r.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity ent)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, ent);
	}


}
