package scapecraft.client.model;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelDragonHelm extends ModelBiped
{
	//fields
	ModelRenderer breathing_hole_1;
	ModelRenderer head_horn_connector_3;
	ModelRenderer head_horn_connector_4;
	ModelRenderer horn_12;
	ModelRenderer horn_11;
	ModelRenderer horn_6;
	ModelRenderer horn_1;
	ModelRenderer left_top_horn;
	ModelRenderer right_bottom_horn_1212;
	ModelRenderer right_top_horn;
	ModelRenderer right_bottom_horn_2;
	ModelRenderer left_bottom_horn_2;
	ModelRenderer thinner_head_horn_connector_12;
	ModelRenderer thinner_head_horn_connector_6;
	ModelRenderer right_bottom_horn_111;
	ModelRenderer head_horn_connector_5;
	ModelRenderer head_horn_connector_6;
	ModelRenderer thinner_head_horn_connector_11;
	ModelRenderer thinner_head_horn_connector_7;
	ModelRenderer thinner_head_horn_connector_8;
	ModelRenderer thinner_head_horn_connector_9;
	ModelRenderer thinner_head_horn_connector_10;
	ModelRenderer horn_2;
	ModelRenderer horn_4;
	ModelRenderer horn_5;
	ModelRenderer horn_3;
	ModelRenderer thinner_head_horn_connector_5;
	ModelRenderer thinner_head_horn_connector_1;
	ModelRenderer thinner_head_horn_connector_2;
	ModelRenderer thinner_head_horn_connector_3;
	ModelRenderer thinner_head_horn_connector_4;
	ModelRenderer head_horn_connector_1;
	ModelRenderer head_horn_connector_2;
	ModelRenderer horn_7;
	ModelRenderer horn_9;
	ModelRenderer horn_8;
	ModelRenderer horn_10;
	ModelRenderer bottom_front_part_2;
	ModelRenderer right_head_flat_part;
	ModelRenderer head;
	ModelRenderer left_flat_head_part;
	ModelRenderer bottom_front_part_1;
	ModelRenderer upper_front_part_1;
	ModelRenderer upper_front_part_2;
	ModelRenderer back_head_part;
	ModelRenderer breathing_hole_6;
	ModelRenderer breathing_hole_2;
	ModelRenderer flat_upper_head_part;
	ModelRenderer front_part_2;
	ModelRenderer breathing_hole_3;
	ModelRenderer front_part_1;
	ModelRenderer breathing_hole_4;
	ModelRenderer breathing_hole_5;
	ModelRenderer left_flat_head_part_2;
	ModelRenderer right_head_flat_part_2;
	ModelRenderer flat_upper_head_part_1;

	public ModelDragonHelm()
	{
		textureWidth = 128;
		textureHeight = 64;

		breathing_hole_1 = new ModelRenderer(this, 0, 35);
		breathing_hole_1.addBox(1.2F, -7F, -2.5F, 2, 1, 1);
		breathing_hole_1.setRotationPoint(0F, 0F, 0F);
		breathing_hole_1.setTextureSize(128, 64);
		breathing_hole_1.mirror = true;
		setRotation(breathing_hole_1, 0.6108652F, -0.1745329F, 0F);
		head_horn_connector_3 = new ModelRenderer(this, 0, 0);
		head_horn_connector_3.addBox(7.5F, -4.1F, 2.2F, 2, 2, 2);
		head_horn_connector_3.setRotationPoint(0F, 0F, 0F);
		head_horn_connector_3.setTextureSize(128, 64);
		head_horn_connector_3.mirror = true;
		setRotation(head_horn_connector_3, 0F, 0F, -0.6108652F);
		head_horn_connector_4 = new ModelRenderer(this, 0, 0);
		head_horn_connector_4.addBox(-9.5F, -4.1F, 2.2F, 2, 2, 2);
		head_horn_connector_4.setRotationPoint(0F, 0F, 0F);
		head_horn_connector_4.setTextureSize(128, 64);
		head_horn_connector_4.mirror = true;
		setRotation(head_horn_connector_4, 0F, 0F, 0.6108652F);
		horn_12 = new ModelRenderer(this, 0, 40);
		horn_12.addBox(5F, -10.3F, 2.7F, 1, 2, 1);
		horn_12.setRotationPoint(0F, 0F, 0F);
		horn_12.setTextureSize(128, 64);
		horn_12.mirror = true;
		setRotation(horn_12, 0F, 0F, 0.0523599F);
		horn_11 = new ModelRenderer(this, 0, 40);
		horn_11.addBox(-6.3F, -10.7F, 2.7F, 1, 1, 1);
		horn_11.setRotationPoint(0F, 0F, 0F);
		horn_11.setTextureSize(128, 64);
		horn_11.mirror = true;
		setRotation(horn_11, 0F, 0F, 1.047198F);
		horn_6 = new ModelRenderer(this, 0, 40);
		horn_6.addBox(-6F, -10.3F, 2.7F, 1, 2, 1);
		horn_6.setRotationPoint(0F, 0F, 0F);
		horn_6.setTextureSize(128, 64);
		horn_6.mirror = true;
		setRotation(horn_6, 0F, 0F, -0.0523599F);
		horn_1 = new ModelRenderer(this, 0, 40);
		horn_1.addBox(5.3F, -10.7F, -3.3F, 1, 1, 1);
		horn_1.setRotationPoint(0F, 0F, 0F);
		horn_1.setTextureSize(128, 64);
		horn_1.mirror = true;
		setRotation(horn_1, 0F, 0F, -1.047198F);
		left_top_horn = new ModelRenderer(this, 0, 40);
		left_top_horn.addBox(-7.3F, -5F, 3.8F, 2, 1, 1);
		left_top_horn.setRotationPoint(0F, 0F, 0F);
		left_top_horn.setTextureSize(128, 64);
		left_top_horn.mirror = true;
		setRotation(left_top_horn, 0F, -0.7853982F, 0F);
		right_bottom_horn_1212 = new ModelRenderer(this, 0, 0);
		right_bottom_horn_1212.addBox(-6.4F, -6F, -1.5F, 1, 3, 3);
		right_bottom_horn_1212.setRotationPoint(0F, 0F, 0F);
		right_bottom_horn_1212.setTextureSize(128, 64);
		right_bottom_horn_1212.mirror = true;
		setRotation(right_bottom_horn_1212, 0F, 0F, 0F);
		right_top_horn = new ModelRenderer(this, 0, 40);
		right_top_horn.addBox(4.9F, -5F, 3.7F, 2, 1, 1);
		right_top_horn.setRotationPoint(0F, 0F, 0F);
		right_top_horn.setTextureSize(128, 64);
		right_top_horn.mirror = true;
		setRotation(right_top_horn, 0F, 0.7853982F, 0F);
		right_bottom_horn_2 = new ModelRenderer(this, 0, 0);
		right_bottom_horn_2.addBox(4.8F, -5.6F, 1.3F, 2, 2, 2);
		right_bottom_horn_2.setRotationPoint(0F, 0F, 0F);
		right_bottom_horn_2.setTextureSize(128, 64);
		right_bottom_horn_2.mirror = true;
		setRotation(right_bottom_horn_2, 0F, 0.4363323F, 0F);
		left_bottom_horn_2 = new ModelRenderer(this, 0, 0);
		left_bottom_horn_2.addBox(-7F, -5.5F, 1.5F, 2, 2, 2);
		left_bottom_horn_2.setRotationPoint(0F, 0F, 0F);
		left_bottom_horn_2.setTextureSize(128, 64);
		left_bottom_horn_2.mirror = true;
		setRotation(left_bottom_horn_2, 0F, -0.4363323F, 0F);
		thinner_head_horn_connector_12 = new ModelRenderer(this, 0, 0);
		thinner_head_horn_connector_12.addBox(-1.6F, -10.2F, 2.8F, 1, 1, 1);
		thinner_head_horn_connector_12.setRotationPoint(0F, 0F, 0F);
		thinner_head_horn_connector_12.setTextureSize(128, 64);
		thinner_head_horn_connector_12.mirror = true;
		setRotation(thinner_head_horn_connector_12, 0F, 0F, -0.5235988F);
		thinner_head_horn_connector_6 = new ModelRenderer(this, 0, 0);
		thinner_head_horn_connector_6.addBox(0.7F, -10.2F, 2.8F, 1, 1, 1);
		thinner_head_horn_connector_6.setRotationPoint(0F, 0F, 0F);
		thinner_head_horn_connector_6.setTextureSize(128, 64);
		thinner_head_horn_connector_6.mirror = true;
		setRotation(thinner_head_horn_connector_6, 0F, 0F, 0.5235988F);
		right_bottom_horn_111 = new ModelRenderer(this, 0, 0);
		right_bottom_horn_111.addBox(5.3F, -6F, -1.5F, 1, 3, 3);
		right_bottom_horn_111.setRotationPoint(0F, 0F, 0F);
		right_bottom_horn_111.setTextureSize(128, 64);
		right_bottom_horn_111.mirror = true;
		setRotation(right_bottom_horn_111, 0F, 0F, 0F);
		head_horn_connector_5 = new ModelRenderer(this, 0, 0);
		head_horn_connector_5.addBox(-9.5F, -4.1F, -3.8F, 2, 2, 2);
		head_horn_connector_5.setRotationPoint(0F, 0F, 0F);
		head_horn_connector_5.setTextureSize(128, 64);
		head_horn_connector_5.mirror = true;
		setRotation(head_horn_connector_5, 0F, 0F, 0.6108652F);
		head_horn_connector_6 = new ModelRenderer(this, 0, 0);
		head_horn_connector_6.addBox(-9.5F, -4.1F, -0.8F, 2, 2, 2);
		head_horn_connector_6.setRotationPoint(0F, 0F, 0F);
		head_horn_connector_6.setTextureSize(128, 64);
		head_horn_connector_6.mirror = true;
		setRotation(head_horn_connector_6, 0F, 0F, 0.6108652F);
		thinner_head_horn_connector_11 = new ModelRenderer(this, 0, 0);
		thinner_head_horn_connector_11.addBox(-1.6F, -10.2F, 2.6F, 1, 1, 1);
		thinner_head_horn_connector_11.setRotationPoint(0F, 0F, 0F);
		thinner_head_horn_connector_11.setTextureSize(128, 64);
		thinner_head_horn_connector_11.mirror = true;
		setRotation(thinner_head_horn_connector_11, 0F, 0F, -0.5235988F);
		thinner_head_horn_connector_7 = new ModelRenderer(this, 0, 0);
		thinner_head_horn_connector_7.addBox(-1.6F, -10.2F, -3.4F, 1, 1, 1);
		thinner_head_horn_connector_7.setRotationPoint(0F, 0F, 0F);
		thinner_head_horn_connector_7.setTextureSize(128, 64);
		thinner_head_horn_connector_7.mirror = true;
		setRotation(thinner_head_horn_connector_7, 0F, 0F, -0.5235988F);
		thinner_head_horn_connector_8 = new ModelRenderer(this, 0, 0);
		thinner_head_horn_connector_8.addBox(-1.6F, -10.2F, -3.2F, 1, 1, 1);
		thinner_head_horn_connector_8.setRotationPoint(0F, 0F, 0F);
		thinner_head_horn_connector_8.setTextureSize(128, 64);
		thinner_head_horn_connector_8.mirror = true;
		setRotation(thinner_head_horn_connector_8, 0F, 0F, -0.5235988F);
		thinner_head_horn_connector_9 = new ModelRenderer(this, 0, 0);
		thinner_head_horn_connector_9.addBox(-1.6F, -10.2F, -0.4F, 1, 1, 1);
		thinner_head_horn_connector_9.setRotationPoint(0F, 0F, 0F);
		thinner_head_horn_connector_9.setTextureSize(128, 64);
		thinner_head_horn_connector_9.mirror = true;
		setRotation(thinner_head_horn_connector_9, 0F, 0F, -0.5235988F);
		thinner_head_horn_connector_10 = new ModelRenderer(this, 0, 0);
		thinner_head_horn_connector_10.addBox(-1.6F, -10.2F, -0.2F, 1, 1, 1);
		thinner_head_horn_connector_10.setRotationPoint(0F, 0F, 0F);
		thinner_head_horn_connector_10.setTextureSize(128, 64);
		thinner_head_horn_connector_10.mirror = true;
		setRotation(thinner_head_horn_connector_10, 0F, 0F, -0.5235988F);
		horn_2 = new ModelRenderer(this, 0, 40);
		horn_2.addBox(-6F, -10.3F, -3.3F, 1, 2, 1);
		horn_2.setRotationPoint(0F, 0F, 0F);
		horn_2.setTextureSize(128, 64);
		horn_2.mirror = true;
		setRotation(horn_2, 0F, 0F, -0.0523599F);
		horn_4 = new ModelRenderer(this, 0, 40);
		horn_4.addBox(-6F, -10.3F, -0.3F, 1, 2, 1);
		horn_4.setRotationPoint(0F, 0F, 0F);
		horn_4.setTextureSize(128, 64);
		horn_4.mirror = true;
		setRotation(horn_4, 0F, 0F, -0.0523599F);
		horn_5 = new ModelRenderer(this, 0, 40);
		horn_5.addBox(5.3F, -10.7F, 2.7F, 1, 1, 1);
		horn_5.setRotationPoint(0F, 0F, 0F);
		horn_5.setTextureSize(128, 64);
		horn_5.mirror = true;
		setRotation(horn_5, 0F, 0F, -1.047198F);
		horn_3 = new ModelRenderer(this, 0, 40);
		horn_3.addBox(5.3F, -10.7F, -0.3F, 1, 1, 1);
		horn_3.setRotationPoint(0F, 0F, 0F);
		horn_3.setTextureSize(128, 64);
		horn_3.mirror = true;
		setRotation(horn_3, 0F, 0F, -1.047198F);
		thinner_head_horn_connector_5 = new ModelRenderer(this, 0, 0);
		thinner_head_horn_connector_5.addBox(0.7F, -10.2F, 2.6F, 1, 1, 1);
		thinner_head_horn_connector_5.setRotationPoint(0F, 0F, 0F);
		thinner_head_horn_connector_5.setTextureSize(128, 64);
		thinner_head_horn_connector_5.mirror = true;
		setRotation(thinner_head_horn_connector_5, 0F, 0F, 0.5235988F);
		thinner_head_horn_connector_1 = new ModelRenderer(this, 0, 0);
		thinner_head_horn_connector_1.addBox(0.7F, -10.2F, -3.4F, 1, 1, 1);
		thinner_head_horn_connector_1.setRotationPoint(0F, 0F, 0F);
		thinner_head_horn_connector_1.setTextureSize(128, 64);
		thinner_head_horn_connector_1.mirror = true;
		setRotation(thinner_head_horn_connector_1, 0F, 0F, 0.5235988F);
		thinner_head_horn_connector_2 = new ModelRenderer(this, 0, 0);
		thinner_head_horn_connector_2.addBox(0.7F, -10.2F, -3.2F, 1, 1, 1);
		thinner_head_horn_connector_2.setRotationPoint(0F, 0F, 0F);
		thinner_head_horn_connector_2.setTextureSize(128, 64);
		thinner_head_horn_connector_2.mirror = true;
		setRotation(thinner_head_horn_connector_2, 0F, 0F, 0.5235988F);
		thinner_head_horn_connector_3 = new ModelRenderer(this, 0, 0);
		thinner_head_horn_connector_3.addBox(0.7F, -10.2F, -0.4F, 1, 1, 1);
		thinner_head_horn_connector_3.setRotationPoint(0F, 0F, 0F);
		thinner_head_horn_connector_3.setTextureSize(128, 64);
		thinner_head_horn_connector_3.mirror = true;
		setRotation(thinner_head_horn_connector_3, 0F, 0F, 0.5235988F);
		thinner_head_horn_connector_4 = new ModelRenderer(this, 0, 0);
		thinner_head_horn_connector_4.addBox(0.7F, -10.2F, -0.2F, 1, 1, 1);
		thinner_head_horn_connector_4.setRotationPoint(0F, 0F, 0F);
		thinner_head_horn_connector_4.setTextureSize(128, 64);
		thinner_head_horn_connector_4.mirror = true;
		setRotation(thinner_head_horn_connector_4, 0F, 0F, 0.5235988F);
		head_horn_connector_1 = new ModelRenderer(this, 0, 0);
		head_horn_connector_1.addBox(7.5F, -4.1F, -3.8F, 2, 2, 2);
		head_horn_connector_1.setRotationPoint(0F, 0F, 0F);
		head_horn_connector_1.setTextureSize(128, 64);
		head_horn_connector_1.mirror = true;
		setRotation(head_horn_connector_1, 0F, 0F, -0.6108652F);
		head_horn_connector_2 = new ModelRenderer(this, 0, 0);
		head_horn_connector_2.addBox(7.5F, -4.1F, -0.8F, 2, 2, 2);
		head_horn_connector_2.setRotationPoint(0F, 0F, 0F);
		head_horn_connector_2.setTextureSize(128, 64);
		head_horn_connector_2.mirror = true;
		setRotation(head_horn_connector_2, 0F, 0F, -0.6108652F);
		horn_7 = new ModelRenderer(this, 0, 40);
		horn_7.addBox(-6.3F, -10.7F, -3.3F, 1, 1, 1);
		horn_7.setRotationPoint(0F, 0F, 0F);
		horn_7.setTextureSize(128, 64);
		horn_7.mirror = true;
		setRotation(horn_7, 0F, 0F, 1.047198F);
		horn_9 = new ModelRenderer(this, 0, 40);
		horn_9.addBox(-6.3F, -10.7F, -0.3F, 1, 1, 1);
		horn_9.setRotationPoint(0F, 0F, 0F);
		horn_9.setTextureSize(128, 64);
		horn_9.mirror = true;
		setRotation(horn_9, 0F, 0F, 1.047198F);
		horn_8 = new ModelRenderer(this, 0, 40);
		horn_8.addBox(5F, -10.3F, -3.3F, 1, 2, 1);
		horn_8.setRotationPoint(0F, 0F, 0F);
		horn_8.setTextureSize(128, 64);
		horn_8.mirror = true;
		setRotation(horn_8, 0F, 0F, 0.0523599F);
		horn_10 = new ModelRenderer(this, 0, 40);
		horn_10.addBox(5F, -10.3F, -0.3F, 1, 2, 1);
		horn_10.setRotationPoint(0F, 0F, 0F);
		horn_10.setTextureSize(128, 64);
		horn_10.mirror = true;
		setRotation(horn_10, 0F, 0F, 0.0523599F);
		bottom_front_part_2 = new ModelRenderer(this, 0, 0);
		bottom_front_part_2.addBox(-2F, -3.5F, -5.2F, 5, 1, 1);
		bottom_front_part_2.setRotationPoint(0F, 0F, 0F);
		bottom_front_part_2.setTextureSize(128, 64);
		bottom_front_part_2.mirror = true;
		setRotation(bottom_front_part_2, 0.4363323F, -0.3490659F, 0F);
		right_head_flat_part = new ModelRenderer(this, 0, 0);
		right_head_flat_part.addBox(4F, -9F, -5F, 1, 9, 10);
		right_head_flat_part.setRotationPoint(0F, 0F, 0F);
		right_head_flat_part.setTextureSize(128, 64);
		right_head_flat_part.mirror = true;
		setRotation(right_head_flat_part, 0F, 0F, 0F);
		head = new ModelRenderer(this, 0, 0);
		head.addBox(-5F, -1F, -5F, 10, 1, 1);
		head.setRotationPoint(0F, 0F, 0F);
		head.setTextureSize(128, 64);
		head.mirror = true;
		setRotation(head, 0F, 0F, 0F);
		left_flat_head_part = new ModelRenderer(this, 0, 0);
		left_flat_head_part.addBox(-4F, -8F, -4F, 1, 9, 10);
		left_flat_head_part.setRotationPoint(-1F, -1F, -1F);
		left_flat_head_part.setTextureSize(128, 64);
		left_flat_head_part.mirror = true;
		setRotation(left_flat_head_part, 0F, 0F, 0F);
		bottom_front_part_1 = new ModelRenderer(this, 0, 0);
		bottom_front_part_1.addBox(-2.7F, -3.5F, -5.2F, 5, 1, 1);
		bottom_front_part_1.setRotationPoint(0F, 0F, 0F);
		bottom_front_part_1.setTextureSize(128, 64);
		bottom_front_part_1.mirror = true;
		setRotation(bottom_front_part_1, 0.4363323F, 0.3316126F, 0F);
		upper_front_part_1 = new ModelRenderer(this, 0, 0);
		upper_front_part_1.addBox(-2.7F, -9F, -6.2F, 5, 3, 1);
		upper_front_part_1.setRotationPoint(0F, 0F, 0F);
		upper_front_part_1.setTextureSize(128, 64);
		upper_front_part_1.mirror = true;
		setRotation(upper_front_part_1, 0F, 0.3316126F, 0F);
		upper_front_part_2 = new ModelRenderer(this, 0, 0);
		upper_front_part_2.addBox(-2F, -9F, -6.2F, 5, 3, 1);
		upper_front_part_2.setRotationPoint(0F, 0F, 0F);
		upper_front_part_2.setTextureSize(128, 64);
		upper_front_part_2.mirror = true;
		setRotation(upper_front_part_2, 0F, -0.3490659F, 0F);
		back_head_part = new ModelRenderer(this, 0, 0);
		back_head_part.addBox(-4F, -9F, 4F, 8, 9, 1);
		back_head_part.setRotationPoint(0F, 0F, 0F);
		back_head_part.setTextureSize(128, 64);
		back_head_part.mirror = true;
		setRotation(back_head_part, 0F, 0F, 0F);
		breathing_hole_6 = new ModelRenderer(this, 0, 35);
		breathing_hole_6.addBox(-3.1F, -5F, -3.9F, 2, 1, 1);
		breathing_hole_6.setRotationPoint(0F, 0F, 0F);
		breathing_hole_6.setTextureSize(128, 64);
		breathing_hole_6.mirror = true;
		setRotation(breathing_hole_6, 0.6108652F, 0.1745329F, 0F);
		breathing_hole_2 = new ModelRenderer(this, 0, 35);
		breathing_hole_2.addBox(1.2F, -6F, -3.2F, 2, 1, 1);
		breathing_hole_2.setRotationPoint(0F, 0F, 0F);
		breathing_hole_2.setTextureSize(128, 64);
		breathing_hole_2.mirror = true;
		setRotation(breathing_hole_2, 0.6108652F, -0.1745329F, 0F);
		flat_upper_head_part = new ModelRenderer(this, 0, 23);
		flat_upper_head_part.addBox(-4F, -8F, -4.9F, 8, 7, 0);
		flat_upper_head_part.setRotationPoint(0F, 0F, 0F);
		flat_upper_head_part.setTextureSize(128, 64);
		flat_upper_head_part.mirror = true;
		setRotation(flat_upper_head_part, 0F, 0F, 0F);
		front_part_2 = new ModelRenderer(this, 0, 0);
		front_part_2.addBox(-2F, -5F, -6.2F, 5, 4, 1);
		front_part_2.setRotationPoint(0F, 0F, 0F);
		front_part_2.setTextureSize(128, 64);
		front_part_2.mirror = true;
		setRotation(front_part_2, 0F, -0.3490659F, 0F);
		breathing_hole_3 = new ModelRenderer(this, 0, 35);
		breathing_hole_3.addBox(1.2F, -5F, -3.9F, 2, 1, 1);
		breathing_hole_3.setRotationPoint(0F, 0F, 0F);
		breathing_hole_3.setTextureSize(128, 64);
		breathing_hole_3.mirror = true;
		setRotation(breathing_hole_3, 0.6108652F, -0.1745329F, 0F);
		front_part_1 = new ModelRenderer(this, 0, 0);
		front_part_1.addBox(-2.7F, -5F, -6.2F, 5, 4, 1);
		front_part_1.setRotationPoint(0F, 0F, 0F);
		front_part_1.setTextureSize(128, 64);
		front_part_1.mirror = true;
		setRotation(front_part_1, 0F, 0.3316126F, 0F);
		breathing_hole_4 = new ModelRenderer(this, 0, 35);
		breathing_hole_4.addBox(-3.1F, -7F, -2.5F, 2, 1, 1);
		breathing_hole_4.setRotationPoint(0F, 0F, 0F);
		breathing_hole_4.setTextureSize(128, 64);
		breathing_hole_4.mirror = true;
		setRotation(breathing_hole_4, 0.6108652F, 0.1745329F, 0F);
		breathing_hole_5 = new ModelRenderer(this, 0, 35);
		breathing_hole_5.addBox(-3.1F, -6F, -3.2F, 2, 1, 1);
		breathing_hole_5.setRotationPoint(0F, 0F, 0F);
		breathing_hole_5.setTextureSize(128, 64);
		breathing_hole_5.mirror = true;
		setRotation(breathing_hole_5, 0.6108652F, 0.1745329F, 0F);
		left_flat_head_part_2 = new ModelRenderer(this, 0, 0);
		left_flat_head_part_2.addBox(-5.4F, -8.5F, -4.5F, 1, 8, 9);
		left_flat_head_part_2.setRotationPoint(0F, 0F, 0F);
		left_flat_head_part_2.setTextureSize(128, 64);
		left_flat_head_part_2.mirror = true;
		setRotation(left_flat_head_part_2, 0F, 0F, 0F);
		right_head_flat_part_2 = new ModelRenderer(this, 0, 0);
		right_head_flat_part_2.addBox(4.3F, -8.5F, -4.5F, 1, 8, 9);
		right_head_flat_part_2.setRotationPoint(0F, 0F, 0F);
		right_head_flat_part_2.setTextureSize(128, 64);
		right_head_flat_part_2.mirror = true;
		setRotation(right_head_flat_part_2, 0F, 0F, 0F);
		flat_upper_head_part_1 = new ModelRenderer(this, 0, 0);
		flat_upper_head_part_1.addBox(-4F, -9F, -5F, 8, 1, 9);
		flat_upper_head_part_1.setRotationPoint(0F, 0F, 0F);
		flat_upper_head_part_1.setTextureSize(128, 64);
		flat_upper_head_part_1.mirror = true;
		setRotation(flat_upper_head_part_1, 0F, 0F, 0F);

		back_head_part.addChild(bottom_front_part_1);
		back_head_part.addChild(bottom_front_part_2);
		back_head_part.addChild(breathing_hole_1);
		back_head_part.addChild(breathing_hole_2);
		back_head_part.addChild(breathing_hole_3);
		back_head_part.addChild(breathing_hole_4);
		back_head_part.addChild(breathing_hole_5);
		back_head_part.addChild(breathing_hole_6);
		back_head_part.addChild(flat_upper_head_part);
		back_head_part.addChild(flat_upper_head_part_1);
		back_head_part.addChild(front_part_1);
		back_head_part.addChild(front_part_2);
		back_head_part.addChild(head);
		back_head_part.addChild(head_horn_connector_1);
		back_head_part.addChild(head_horn_connector_2);
		back_head_part.addChild(head_horn_connector_3);
		back_head_part.addChild(head_horn_connector_4);
		back_head_part.addChild(head_horn_connector_5);
		back_head_part.addChild(head_horn_connector_6);
		back_head_part.addChild(horn_1);
		back_head_part.addChild(horn_10);
		back_head_part.addChild(horn_11);
		back_head_part.addChild(horn_12);
		back_head_part.addChild(horn_2);
		back_head_part.addChild(horn_3);
		back_head_part.addChild(horn_4);
		back_head_part.addChild(horn_5);
		back_head_part.addChild(horn_6);
		back_head_part.addChild(horn_7);
		back_head_part.addChild(horn_8);
		back_head_part.addChild(horn_9);
		back_head_part.addChild(left_bottom_horn_2);
		back_head_part.addChild(left_flat_head_part);
		back_head_part.addChild(left_flat_head_part_2);
		back_head_part.addChild(left_top_horn);
		back_head_part.addChild(right_bottom_horn_111);
		back_head_part.addChild(right_bottom_horn_1212);
		back_head_part.addChild(right_bottom_horn_2);
		back_head_part.addChild(right_head_flat_part);
		back_head_part.addChild(right_head_flat_part_2);
		back_head_part.addChild(right_top_horn);
		back_head_part.addChild(thinner_head_horn_connector_1);
		back_head_part.addChild(thinner_head_horn_connector_10);
		back_head_part.addChild(thinner_head_horn_connector_11);
		back_head_part.addChild(thinner_head_horn_connector_12);
		back_head_part.addChild(thinner_head_horn_connector_2);
		back_head_part.addChild(thinner_head_horn_connector_3);
		back_head_part.addChild(thinner_head_horn_connector_4);
		back_head_part.addChild(thinner_head_horn_connector_5);
		back_head_part.addChild(thinner_head_horn_connector_6);
		back_head_part.addChild(thinner_head_horn_connector_7);
		back_head_part.addChild(thinner_head_horn_connector_8);
		back_head_part.addChild(thinner_head_horn_connector_9);
		back_head_part.addChild(upper_front_part_1);
		back_head_part.addChild(upper_front_part_2);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		back_head_part.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		this.back_head_part.rotateAngleY = this.bipedHead.rotateAngleY;
		this.back_head_part.rotateAngleX = this.bipedHead.rotateAngleX;
	}

}
