package scapecraft.client;

import net.minecraft.client.renderer.entity.RenderTNTPrimed;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.client.MinecraftForgeClient;

import scapecraft.Scapecraft;
import scapecraft.client.model.ModelAbbyDemon;
import scapecraft.client.model.ModelAhrim;
import scapecraft.client.model.ModelAkrisae;
import scapecraft.client.model.ModelBlackDemon;
import scapecraft.client.model.ModelCaveCrawler;
import scapecraft.client.model.ModelDharok;
import scapecraft.client.model.ModelDwarf;
import scapecraft.client.model.ModelFireGiant;
import scapecraft.client.model.ModelGeneralGraardor;
import scapecraft.client.model.ModelGhost;
import scapecraft.client.model.ModelGoblin;
import scapecraft.client.model.ModelGreenDragon;
import scapecraft.client.model.ModelGuthan;
import scapecraft.client.model.ModelHellhound;
import scapecraft.client.model.ModelHillGiant;
import scapecraft.client.model.ModelIceGiant;
import scapecraft.client.model.ModelKK;
import scapecraft.client.model.ModelKKspawn;
import scapecraft.client.model.ModelKQ;
import scapecraft.client.model.ModelKQ2;
import scapecraft.client.model.ModelKaril;
import scapecraft.client.model.ModelLavaBlock;
import scapecraft.client.model.ModelLesserDemon;
import scapecraft.client.model.ModelLesserDemon2;
import scapecraft.client.model.ModelLootChest;
import scapecraft.client.model.ModelMagicBoat;
import scapecraft.client.model.ModelMossGiant;
import scapecraft.client.model.ModelRat;
import scapecraft.client.model.ModelScorpion;
import scapecraft.client.model.ModelSergeantGrimSpike;
import scapecraft.client.model.ModelSergeantSteelWill;
import scapecraft.client.model.ModelSergeantStrongStack;
import scapecraft.client.model.ModelTD;
import scapecraft.client.model.ModelTorag;
import scapecraft.client.model.ModelVerac;
import scapecraft.client.renderer.RenderBipedScapecraft;
import scapecraft.client.renderer.RenderEntityScapecraft;
import scapecraft.client.renderer.item.ItemRenderHammer;
import scapecraft.entity.EntityAbbyDemon;
import scapecraft.entity.EntityAhrim;
import scapecraft.entity.EntityAkrisae;
import scapecraft.entity.EntityBandit;
import scapecraft.entity.EntityBarbarian;
import scapecraft.entity.EntityBlackDemon;
import scapecraft.entity.EntityBlackDragon;
import scapecraft.entity.EntityBlackGuard;
import scapecraft.entity.EntityBlackGuard2;
import scapecraft.entity.EntityBlackKnight;
import scapecraft.entity.EntityBot;
import scapecraft.entity.EntityBot2;
import scapecraft.entity.EntityBot3;
import scapecraft.entity.EntityCaveCrawler;
import scapecraft.entity.EntityCook;
import scapecraft.entity.EntityDarkwizard;
import scapecraft.entity.EntityDharok;
import scapecraft.entity.EntityDoctor;
import scapecraft.entity.EntityDwarf;
import scapecraft.entity.EntityEliteBlackKnight;
import scapecraft.entity.EntityFarmer;
import scapecraft.entity.EntityFireGiant;
import scapecraft.entity.EntityFremGuard;
import scapecraft.entity.EntityGeneralGraardor;
import scapecraft.entity.EntityGhost;
import scapecraft.entity.EntityGoblin;
import scapecraft.entity.EntityGreenDragon;
import scapecraft.entity.EntityGuard;
import scapecraft.entity.EntityGuthan;
import scapecraft.entity.EntityHellhound;
import scapecraft.entity.EntityHeroKnight;
import scapecraft.entity.EntityHighMage;
import scapecraft.entity.EntityHillGiant;
import scapecraft.entity.EntityIceGiant;
import scapecraft.entity.EntityIronDragon;
import scapecraft.entity.EntityKK;
import scapecraft.entity.EntityKKspawn;
import scapecraft.entity.EntityKQ;
import scapecraft.entity.EntityKQ2;
import scapecraft.entity.EntityKaril;
import scapecraft.entity.EntityKing;
import scapecraft.entity.EntityKingsGuard;
import scapecraft.entity.EntityKos1;
import scapecraft.entity.EntityKos2;
import scapecraft.entity.EntityKos3;
import scapecraft.entity.EntityKos4;
import scapecraft.entity.EntityLavaBlock;
import scapecraft.entity.EntityLesserDemon;
import scapecraft.entity.EntityLesserDemon2;
import scapecraft.entity.EntityLootChest;
import scapecraft.entity.EntityMagicBoat;
import scapecraft.entity.EntityMan;
import scapecraft.entity.EntityMorgan;
import scapecraft.entity.EntityMossGiant;
import scapecraft.entity.EntityMugger;
import scapecraft.entity.EntityRat;
import scapecraft.entity.EntityRatSmall;
import scapecraft.entity.EntityScorpion;
import scapecraft.entity.EntitySergeantGrimspike;
import scapecraft.entity.EntitySergeantSteelwill;
import scapecraft.entity.EntitySergeantStrongstack;
import scapecraft.entity.EntityShopKeeper;
import scapecraft.entity.EntityTD;
import scapecraft.entity.EntityTNTXPrimed;
import scapecraft.entity.EntityTheif;
import scapecraft.entity.EntityTinyTNTPrimed;
import scapecraft.entity.EntityTorag;
import scapecraft.entity.EntityVampire;
import scapecraft.entity.EntityVarze;
import scapecraft.entity.EntityVerac;
import scapecraft.entity.EntityWhiteKnight;
import scapecraft.entity.EntityWizard;

import cpw.mods.fml.client.registry.RenderingRegistry;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;

@SideOnly(Side.CLIENT)
public class ClientProxy
{
	public static void registerRenderers()
	{
		MinecraftForgeClient.registerItemRenderer(Scapecraft.steelHammer, new ItemRenderHammer(Resources.TEXTURE_SteelHammer));
		MinecraftForgeClient.registerItemRenderer(Scapecraft.mithHammer, new ItemRenderHammer(Resources.TEXTURE_MithHammer));
		MinecraftForgeClient.registerItemRenderer(Scapecraft.addyHammer, new ItemRenderHammer(Resources.TEXTURE_AddyHammer));
		MinecraftForgeClient.registerItemRenderer(Scapecraft.runeHammer, new ItemRenderHammer(Resources.TEXTURE_RuneHammer));

		RenderingRegistry.registerEntityRenderingHandler(EntityBandit.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/bandit.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityBarbarian.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/barbarian.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityBlackGuard.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/blackboss.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityBlackGuard2.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/blackboss.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityBlackKnight.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/Theif.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityBot.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/bot.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityBot2.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/bot2.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityBot3.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/bot.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityCook.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/cook.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityDarkwizard.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/darkwizard.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityDoctor.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/doctor.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityEliteBlackKnight.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/Theif.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityFarmer.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/farmer.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityFremGuard.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/fremguard.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityGuard.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/guard.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityHeroKnight.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/whiteknight.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityHighMage.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/highmage.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityKing.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/king.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityKingsGuard.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/kingguard.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityKos1.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/Kos.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityKos2.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/Kos.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityKos3.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/Kos.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityKos4.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/Kos2.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityMan.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/man.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityMorgan.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/morgan.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityMugger.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/mugger.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityShopKeeper.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/shopkeeper.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityTheif.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/Theif.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityVampire.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/vampire.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityVarze.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/varze.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityWhiteKnight.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/whiteknight.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityWizard.class, new RenderBipedScapecraft(new ResourceLocation("scapecraft", "textures/entity/wizard.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityAbbyDemon.class, new RenderEntityScapecraft(new ModelAbbyDemon(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/abbydemon.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityAhrim.class, new RenderEntityScapecraft(new ModelAhrim(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/Ahrim.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityAkrisae.class, new RenderEntityScapecraft(new ModelAkrisae(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/Akrisae.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityBlackDemon.class, new RenderEntityScapecraft(new ModelBlackDemon(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/BlackDemon.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityBlackDragon.class, new RenderEntityScapecraft(new ModelGreenDragon(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/BlackDragon.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityCaveCrawler.class, new RenderEntityScapecraft(new ModelCaveCrawler(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/CaveCrawler.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityDharok.class, new RenderEntityScapecraft(new ModelDharok(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/Dharok.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityDwarf.class, new RenderEntityScapecraft(new ModelDwarf(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/dwarf.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityFireGiant.class, new RenderEntityScapecraft(new ModelFireGiant(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/FireGiant.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityGeneralGraardor.class, new RenderEntityScapecraft(new ModelGeneralGraardor(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/GeneralGraardor.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityGhost.class, new RenderEntityScapecraft(new ModelGhost(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/GhostF.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityGoblin.class, new RenderEntityScapecraft(new ModelGoblin(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/goblin.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityGreenDragon.class, new RenderEntityScapecraft(new ModelGreenDragon(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/GreenDragon.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityGuthan.class, new RenderEntityScapecraft(new ModelGuthan(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/Guthan.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityHellhound.class, new RenderEntityScapecraft(new ModelHellhound(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/HellHound.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityHillGiant.class, new RenderEntityScapecraft(new ModelHillGiant(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/HillGiant.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityIceGiant.class, new RenderEntityScapecraft(new ModelIceGiant(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/IceGiant.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityIronDragon.class, new RenderEntityScapecraft(new ModelGreenDragon(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/IronDragon.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityKK.class, new RenderEntityScapecraft(new ModelKK(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/KK.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityKKspawn.class, new RenderEntityScapecraft(new ModelKKspawn(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/KKspawn.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityKQ.class, new RenderEntityScapecraft(new ModelKQ(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/KQ.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityKQ2.class, new RenderEntityScapecraft(new ModelKQ2(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/KQ2.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityKaril.class, new RenderEntityScapecraft(new ModelKaril(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/Karil.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityLavaBlock.class, new RenderEntityScapecraft(new ModelLavaBlock(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/LavaBlock.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityLesserDemon.class, new RenderEntityScapecraft(new ModelLesserDemon(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/LesserDemon.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityLesserDemon2.class, new RenderEntityScapecraft(new ModelLesserDemon2(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/LesserDemon2.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityLootChest.class, new RenderEntityScapecraft(new ModelLootChest(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/Chest.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityMagicBoat.class, new RenderEntityScapecraft(new ModelMagicBoat(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/magicboat.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityMossGiant.class, new RenderEntityScapecraft(new ModelMossGiant(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/MossGiant.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityRat.class, new RenderEntityScapecraft(new ModelRat(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/rat.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityRatSmall.class, new RenderEntityScapecraft(new ModelRat(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/rat.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityScorpion.class, new RenderEntityScapecraft(new ModelScorpion(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/scorpian.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntitySergeantGrimspike.class, new RenderEntityScapecraft(new ModelSergeantGrimSpike(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/SergeantGrimspike.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntitySergeantSteelwill.class, new RenderEntityScapecraft(new ModelSergeantSteelWill(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/SergeantSteelwill.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntitySergeantStrongstack.class, new RenderEntityScapecraft(new ModelSergeantStrongStack(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/SergeantStrongstack.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityTD.class, new RenderEntityScapecraft(new ModelTD(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/TD.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityTNTXPrimed.class, new RenderTNTPrimed());
		RenderingRegistry.registerEntityRenderingHandler(EntityTinyTNTPrimed.class, new RenderTNTPrimed());
		RenderingRegistry.registerEntityRenderingHandler(EntityTorag.class, new RenderEntityScapecraft(new ModelTorag(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/ToragWHammers.png")));
		RenderingRegistry.registerEntityRenderingHandler(EntityVerac.class, new RenderEntityScapecraft(new ModelVerac(), 0.5F, new ResourceLocation("scapecraft", "textures/entity/Verac.png")));
	}
}
