package scapecraft.entity;

import static scapecraft.entity.EntityScapecraft.addDrop;

import java.util.HashMap;

import net.minecraft.entity.Entity;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;

import scapecraft.Scapecraft;
import scapecraft.block.ScapecraftBlocks;
import scapecraft.item.ItemScapecraftSpawnEgg;
import scapecraft.item.ScapecraftItems;
import scapecraft.util.CombatXpHelper;

import cpw.mods.fml.common.registry.EntityRegistry;

public class ScapecraftEntities
{
	private static int currentEntityIdOffset = 0;

	public static HashMap<String, Class<? extends Entity>> entityNames = new HashMap<String, Class<? extends Entity>>();
	
	public static void registerEntities()
	{
		registerEntity(EntityAbbyDemon.class, "AbbyDemon");
		registerEntity(EntityAhrim.class, "Ahrim");
		registerEntity(EntityAkrisae.class, "Akrisae");
		registerEntity(EntityBandit.class, "Bandit");
		registerEntity(EntityBarbarian.class, "Barbarian");
		registerEntity(EntityBlackDemon.class, "BlackDemon");
		registerEntity(EntityBlackDragon.class, "BlackDragon");
		registerEntity(EntityBlackGuard2.class, "BlackGuard2");
		registerEntity(EntityBlackGuard.class, "BlackGuard");
		registerEntity(EntityBlackKnight.class, "BlackKnight");
		registerEntity(EntityBot2.class, "Bot2");
		registerEntity(EntityBot3.class, "Bot3");
		registerEntity(EntityBot.class, "Bot");
		registerEntity(EntityCaveCrawler.class, "CaveCrawler");
		registerEntity(EntityCook.class, "Cook");
		registerEntity(EntityDarkwizard.class, "Darkwizard");
		registerEntity(EntityDharok.class, "Dharok");
		registerEntity(EntityDoctor.class, "Doctor");
		registerEntity(EntityDwarf.class, "Dwarf");
		registerEntity(EntityEliteBlackKnight.class, "EliteBlackKnight");
		registerEntity(EntityFarmer.class, "Farmer");
		registerEntity(EntityFireGiant.class, "FireGiant");
		registerEntity(EntityFremGuard.class, "FremGuard");
		registerEntity(EntityGeneralGraardor.class, "GeneralGraardor");
		registerEntity(EntityGhost.class, "Ghost");
		registerEntity(EntityGoblin.class, "Goblin");
		registerEntity(EntityGreenDragon.class, "GreenDragon");
		registerEntity(EntityGuard.class, "Guard");
		registerEntity(EntityGuthan.class, "Guthan");
		registerEntity(EntityHellhound.class, "Hellhound");
		registerEntity(EntityHeroKnight.class, "HeroKnight");
		registerEntity(EntityHighMage.class, "HighMage");
		registerEntity(EntityHillGiant.class, "HillGiant");
		registerEntity(EntityIceGiant.class, "IceGiant");
		registerEntity(EntityIronDragon.class, "IronDragon");
		registerEntity(EntityKaril.class, "Karil");
		registerEntity(EntityKing.class, "King");
		registerEntity(EntityKingsGuard.class, "KingsGuard");
		registerEntity(EntityKK.class, "KK");
		registerEntity(EntityKKspawn.class, "KKspawn");
		registerEntity(EntityKos1.class, "Kos1");
		registerEntity(EntityKos2.class, "Kos2");
		registerEntity(EntityKos3.class, "Kos3");
		registerEntity(EntityKos4.class, "Kos4");
		registerEntity(EntityKQ2.class, "KQ2");
		registerEntity(EntityKQ.class, "KQ");
		registerEntity(EntityLavaBlock.class, "LavaBlock");
		registerEntity(EntityLesserDemon2.class, "LesserDemon2");
		registerEntity(EntityLesserDemon.class, "LesserDemon");
		registerEntity(EntityLootChest.class, "LootChest");
		registerEntity(EntityMagicBoat.class, "MagicBoat");
		registerEntity(EntityMan.class, "Man");
		registerEntity(EntityMorgan.class, "Morgan");
		registerEntity(EntityMossGiant.class, "MossGiant");
		registerEntity(EntityMugger.class, "Mugger");
		registerEntity(EntityRat.class, "Rat");
		registerEntity(EntityRatSmall.class, "RatSmall");
		registerEntity(EntityScorpion.class, "Scorpion");
		registerEntity(EntitySergeantGrimspike.class, "SergeantGrimspike");
		registerEntity(EntitySergeantSteelwill.class, "SergeantSteelwill");
		registerEntity(EntitySergeantStrongstack.class, "SergeantStrongstack");
		registerEntity(EntityShopKeeper.class, "ShopKeeper");
		registerEntity(EntityTD.class, "TD");
		registerEntity(EntityTheif.class, "Theif");
		registerEntity(EntityTorag.class, "Torag");
		registerEntity(EntityVampire.class, "Vampire");
		registerEntity(EntityVarze.class, "Varze");
		registerEntity(EntityVerac.class, "Verac");
		registerEntity(EntityWhiteKnight.class, "WhiteKnight");
		registerEntity(EntityWizard.class, "Wizard");
		registerEntity(EntityZilyana.class, "Zilyana");
		registerEntity(EntityZaklnGritch.class, "ZaklnGritch");
		registerEntity(EntityTstanonKarlak.class, "TstanonKarlak");
		registerEntity(EntityKrilTsutsaroth.class, "KrilTsutsaroth");
		registerEntity(EntityBalfrugKreeyath.class, "BalfrugKreeyath");

		CombatXpHelper.addVanilla();
	}

	public static void registerEntity(Class<? extends Entity> entityClass, String name)
	{
		EntityRegistry.registerModEntity(entityClass, name, currentEntityIdOffset, Scapecraft.instance, 80, 3, true);
		entityNames.put(name, entityClass);
		if(EntityScapecraft.class.isAssignableFrom(entityClass))
			ItemScapecraftSpawnEgg.addEntity(name);
		currentEntityIdOffset++;
	}

	public static void addDrops()
	{
		addDrop(EntityAbbyDemon.class, 1000, new ItemStack(ScapecraftItems.whip));
		addDrop(EntityAbbyDemon.class, 2, new ItemStack(Items.gold_nugget));
		addDrop(EntityAbbyDemon.class, 30, new ItemStack(ScapecraftItems.blackChestplate));
		addDrop(EntityAbbyDemon.class, 3000, new ItemStack(ScapecraftItems.dragonScimmy));
		addDrop(EntityAbbyDemon.class, 50, new ItemStack(ScapecraftBlocks.addyOre));
		addDrop(EntityAbbyDemon.class, 50, new ItemStack(ScapecraftItems.mithLeggings));
		addDrop(EntityAhrim.class, 1, new ItemStack(ScapecraftItems.ahrimKey));
		addDrop(EntityAhrim.class, 300, new ItemStack(ScapecraftItems.ahrimBoots));
		addDrop(EntityAhrim.class, 300, new ItemStack(ScapecraftItems.ahrimChestplate));
		addDrop(EntityAhrim.class, 300, new ItemStack(ScapecraftItems.ahrimHelmet));
		addDrop(EntityAhrim.class, 300, new ItemStack(ScapecraftItems.ahrimLeggings));
		addDrop(EntityAhrim.class, 400, new ItemStack(ScapecraftItems.ahrimStaff));
		addDrop(EntityAhrim.class, 800, new ItemStack(ScapecraftItems.dragonLeggings));
		addDrop(EntityAkrisae.class, 1, new ItemStack(ScapecraftItems.akrisaeKey));
		addDrop(EntityAkrisae.class, 300, new ItemStack(ScapecraftItems.akrisaeBoots));
		addDrop(EntityAkrisae.class, 300, new ItemStack(ScapecraftItems.akrisaeChestplate));
		addDrop(EntityAkrisae.class, 300, new ItemStack(ScapecraftItems.akrisaeHelmet));
		addDrop(EntityAkrisae.class, 300, new ItemStack(ScapecraftItems.akrisaeLeggings));
		addDrop(EntityAkrisae.class, 400, new ItemStack(ScapecraftItems.akrisaeMace));
		addDrop(EntityAkrisae.class, 800, new ItemStack(ScapecraftItems.dragonLeggings));
		addDrop(EntityBandit.class, 1, new ItemStack(ScapecraftItems.blackSword));
		addDrop(EntityBandit.class, 1, new ItemStack(ScapecraftItems.fishPie, 3));
		addDrop(EntityBandit.class, 10, new ItemStack(Blocks.coal_block));
		addDrop(EntityBandit.class, 10, new ItemStack(Items.gold_ingot));
		addDrop(EntityBandit.class, 10, new ItemStack(ScapecraftItems.addyHammer));
		addDrop(EntityBandit.class, 10, new ItemStack(ScapecraftItems.addySword));
		addDrop(EntityBandit.class, 10, new ItemStack(ScapecraftItems.blackHalberd));
		addDrop(EntityBandit.class, 30, new ItemStack(ScapecraftItems.dragonLongsword));
		addDrop(EntityBandit.class, 300, new ItemStack(ScapecraftItems.keris));
		addDrop(EntityBandit.class, 40, new ItemStack(ScapecraftItems.blackgLeggings));
		addDrop(EntityBarbarian.class, 140, new ItemStack(ScapecraftItems.whiteBoots));
		addDrop(EntityBarbarian.class, 140, new ItemStack(ScapecraftItems.whiteHelmet));
		addDrop(EntityBarbarian.class, 141, new ItemStack(ScapecraftItems.whiteSword));
		addDrop(EntityBarbarian.class, 16, new ItemStack(Items.gold_nugget));
		addDrop(EntityBarbarian.class, 160, new ItemStack(ScapecraftItems.whiteChestplate));
		addDrop(EntityBarbarian.class, 160, new ItemStack(ScapecraftItems.whiteLeggings));
		addDrop(EntityBarbarian.class, 3500, new ItemStack(ScapecraftItems.dragonLeggings));
		addDrop(EntityBarbarian.class, 500, new ItemStack(ScapecraftItems.bandosHelmet));
		addDrop(EntityBlackDemon.class, 20, new ItemStack(ScapecraftBlocks.runeOre));
		addDrop(EntityBlackDemon.class, 2000, new ItemStack(ScapecraftItems.chaoticMaul));
		addDrop(EntityBlackDemon.class, 2000, new ItemStack(ScapecraftItems.chaoticRapier));
		addDrop(EntityBlackDemon.class, 40, new ItemStack(ScapecraftItems.blackHalberd));
		addDrop(EntityBlackDemon.class, 5, new ItemStack(ScapecraftItems.mithHelmet));
		addDrop(EntityBlackDemon.class, 5, new ItemStack(ScapecraftItems.whiteChestplate));
		addDrop(EntityBlackDemon.class, 700, new ItemStack(ScapecraftItems.DBA));
		addDrop(EntityBlackDemon.class, 700, new ItemStack(ScapecraftItems.shard3));
		addDrop(EntityBlackDragon.class, 1, new ItemStack(ScapecraftItems.blackDHide));
		addDrop(EntityBlackDragon.class, 1000, new ItemStack(ScapecraftItems.armadylHilt));
		addDrop(EntityBlackDragon.class, 15, new ItemStack(ScapecraftItems.mithBoots));
		addDrop(EntityBlackDragon.class, 2, new ItemStack(ScapecraftBlocks.addyOre));
		addDrop(EntityBlackDragon.class, 5, new ItemStack(Items.gold_ingot));
		addDrop(EntityBlackDragon.class, 500, new ItemStack(ScapecraftItems.dragonScimmy));
		addDrop(EntityBlackDragon.class, 500, new ItemStack(ScapecraftItems.runeChestplate));
		addDrop(EntityBlackDragon.class, 500, new ItemStack(ScapecraftItems.shard1));
		addDrop(EntityBlackDragon.class, 500000, new ItemStack(ScapecraftItems.dragonChestplate));
		addDrop(EntityBlackGuard.class, 1, new ItemStack(Items.gold_nugget));
		addDrop(EntityBlackGuard.class, 100, new ItemStack(ScapecraftItems.blackHalberd));
		addDrop(EntityBlackGuard.class, 1000, new ItemStack(ScapecraftItems.dragonLeggings));
		addDrop(EntityBlackGuard.class, 14, new ItemStack(ScapecraftItems.blackBoots));
		addDrop(EntityBlackGuard.class, 141, new ItemStack(ScapecraftItems.blackSword));
		addDrop(EntityBlackGuard.class, 16, new ItemStack(ScapecraftItems.blackChestplate));
		addDrop(EntityBlackGuard.class, 16, new ItemStack(ScapecraftItems.blackLeggings));
		addDrop(EntityBlackGuard2.class, 1, new ItemStack(ScapecraftItems.doorKey, 2));
		addDrop(EntityBlackGuard2.class, 100, new ItemStack(ScapecraftItems.blackHalberd));
		addDrop(EntityBlackGuard2.class, 1000, new ItemStack(ScapecraftItems.dragonLeggings));
		addDrop(EntityBlackGuard2.class, 14, new ItemStack(ScapecraftItems.blackBoots));
		addDrop(EntityBlackGuard2.class, 141, new ItemStack(ScapecraftItems.blackSword));
		addDrop(EntityBlackGuard2.class, 16, new ItemStack(ScapecraftItems.blackChestplate));
		addDrop(EntityBlackGuard2.class, 16, new ItemStack(ScapecraftItems.blackLeggings));
		addDrop(EntityBlackKnight.class, 140, new ItemStack(ScapecraftItems.blackBoots));
		addDrop(EntityBlackKnight.class, 140, new ItemStack(ScapecraftItems.blackHelmet));
		addDrop(EntityBlackKnight.class, 141, new ItemStack(ScapecraftItems.blackSword));
		addDrop(EntityBlackKnight.class, 160, new ItemStack(ScapecraftItems.blackChestplate));
		addDrop(EntityBlackKnight.class, 160, new ItemStack(ScapecraftItems.blackLeggings));
		addDrop(EntityBlackKnight.class, 3000, new ItemStack(ScapecraftItems.dragonLeggings));
		addDrop(EntityBlackKnight.class, 4, new ItemStack(Items.gold_nugget));
		addDrop(EntityBot.class, 1000, new ItemStack(ScapecraftBlocks.magicSapling));
		addDrop(EntityBot.class, 30, new ItemStack(Items.wooden_axe));
		addDrop(EntityBot.class, 30, new ItemStack(Items.wooden_hoe));
		addDrop(EntityBot.class, 30000, new ItemStack(ScapecraftItems.korasis));
		addDrop(EntityBot.class, 33000, new ItemStack(ScapecraftItems.dragonLongsword));
		addDrop(EntityBot.class, 80000, new ItemStack(ScapecraftItems.dragonPickaxe));
		addDrop(EntityBot2.class, 15000, new ItemStack(ScapecraftItems.korasis));
		addDrop(EntityBot2.class, 20000, new ItemStack(ScapecraftItems.dragonAxe));
		addDrop(EntityBot2.class, 20000, new ItemStack(ScapecraftItems.dragonLongsword));
		addDrop(EntityBot2.class, 25000, new ItemStack(ScapecraftItems.dragonHelmet));
		addDrop(EntityBot2.class, 35, new ItemStack(Items.stone_axe));
		addDrop(EntityBot2.class, 35, new ItemStack(Items.stone_axe));
		addDrop(EntityBot3.class, 1500, new ItemStack(ScapecraftItems.runegChestplate));
		addDrop(EntityBot3.class, 1750, new ItemStack(ScapecraftItems.dragonBoots));
		addDrop(EntityBot3.class, 30, new ItemStack(Items.stone_sword));
		addDrop(EntityBot3.class, 60, new ItemStack(ScapecraftItems.addyHelmet));
		addDrop(EntityCaveCrawler.class, 100, new ItemStack(ScapecraftItems.magicFruit));
		addDrop(EntityCaveCrawler.class, 15, new ItemStack(Items.wooden_sword));
		addDrop(EntityCaveCrawler.class, 3000, new ItemStack(ScapecraftItems.runegBoots));
		addDrop(EntityCaveCrawler.class, 30000, new ItemStack(ScapecraftItems.crystalBow));
		addDrop(EntityCaveCrawler.class, 400, new ItemStack(ScapecraftItems.runeSword));
		addDrop(EntityCaveCrawler.class, 6, new ItemStack(Items.gold_nugget));
		addDrop(EntityDarkwizard.class, 1100, new ItemStack(ScapecraftItems.guthixStaff));
		addDrop(EntityDarkwizard.class, 5000, new ItemStack(ScapecraftItems.zamorakHilt));
		addDrop(EntityDarkwizard.class, 600, new ItemStack(ScapecraftItems.zammyStaff));
		addDrop(EntityDarkwizard.class, 8, new ItemStack(Items.gold_nugget));
		addDrop(EntityDarkwizard.class, 8, new ItemStack(ScapecraftItems.barrowsTab));
		addDrop(EntityDarkwizard.class, 8, new ItemStack(ScapecraftItems.bandosTab));
		addDrop(EntityDarkwizard.class, 8, new ItemStack(ScapecraftItems.cathTab));
		addDrop(EntityDarkwizard.class, 8, new ItemStack(ScapecraftItems.faladorTab));
		addDrop(EntityDarkwizard.class, 8, new ItemStack(ScapecraftItems.hubTab));
		addDrop(EntityDarkwizard.class, 8, new ItemStack(ScapecraftItems.lumbridgeTab));
		addDrop(EntityDarkwizard.class, 8, new ItemStack(ScapecraftItems.tormentedDemonsTab));
		addDrop(EntityDarkwizard.class, 8, new ItemStack(ScapecraftItems.varrockTeletab));
		addDrop(EntityDharok.class, 1, new ItemStack(ScapecraftItems.dharokKey));
		addDrop(EntityDharok.class, 300, new ItemStack(ScapecraftItems.dharokBoots));
		addDrop(EntityDharok.class, 300, new ItemStack(ScapecraftItems.dharokChestplate));
		addDrop(EntityDharok.class, 300, new ItemStack(ScapecraftItems.dharokHelmet));
		addDrop(EntityDharok.class, 300, new ItemStack(ScapecraftItems.dharokLeggings));
		addDrop(EntityDharok.class, 400, new ItemStack(ScapecraftItems.dharokAxe));
		addDrop(EntityDharok.class, 400, new ItemStack(ScapecraftItems.dragonLeggings));
		addDrop(EntityDwarf.class, 100, new ItemStack(ScapecraftItems.blackLeggings));
		addDrop(EntityDwarf.class, 100, new ItemStack(ScapecraftItems.magicFruit));
		addDrop(EntityDwarf.class, 15, new ItemStack(Items.wooden_pickaxe));
		addDrop(EntityDwarf.class, 2400, new ItemStack(ScapecraftItems.dragonPickaxe));
		addDrop(EntityEliteBlackKnight.class, 1, new ItemStack(Items.gold_nugget));
		addDrop(EntityEliteBlackKnight.class, 1000, new ItemStack(ScapecraftItems.dragonLeggings));
		addDrop(EntityEliteBlackKnight.class, 3, new ItemStack(ScapecraftItems.blackSword));
		addDrop(EntityEliteBlackKnight.class, 500, new ItemStack(ScapecraftItems.blackHalberd));
		addDrop(EntityEliteBlackKnight.class, 500, new ItemStack(ScapecraftItems.blackgBoots));
		addDrop(EntityEliteBlackKnight.class, 500, new ItemStack(ScapecraftItems.blackgChestplate));
		addDrop(EntityEliteBlackKnight.class, 500, new ItemStack(ScapecraftItems.blackgHelmet));
		addDrop(EntityEliteBlackKnight.class, 500, new ItemStack(ScapecraftItems.blackgLeggings));
		addDrop(EntityFarmer.class, 140, new ItemStack(ScapecraftItems.guardHelmet));
		addDrop(EntityFarmer.class, 15, new ItemStack(Items.stone_sword));
		addDrop(EntityFarmer.class, 160, new ItemStack(ScapecraftItems.guardChestplate));
		addDrop(EntityFarmer.class, 40, new ItemStack(ScapecraftItems.pitchFork));
		addDrop(EntityFireGiant.class, 1, new ItemStack(Items.gold_nugget));
		addDrop(EntityFireGiant.class, 10, new ItemStack(ScapecraftItems.blackChestplate));
		addDrop(EntityFireGiant.class, 1000, new ItemStack(ScapecraftItems.darkBow));
		addDrop(EntityFireGiant.class, 20, new ItemStack(ScapecraftItems.graniteLump));
		addDrop(EntityFireGiant.class, 2000, new ItemStack(ScapecraftItems.dragonLeggings));
		addDrop(EntityFireGiant.class, 300, new ItemStack(ScapecraftItems.dragonLongsword));
		addDrop(EntityFireGiant.class, 40, new ItemStack(ScapecraftItems.runeBoots));
		addDrop(EntityFireGiant.class, 400, new ItemStack(ScapecraftItems.dragonHelmet));
		addDrop(EntityFireGiant.class, 5, new ItemStack(Blocks.obsidian));
		addDrop(EntityFireGiant.class, 60, new ItemStack(ScapecraftItems.addyChestplate));
		addDrop(EntityFireGiant.class, 7, new ItemStack(ScapecraftItems.whiteBoots));
		addDrop(EntityFireGiant.class, 8, new ItemStack(ScapecraftBlocks.mithOre));
		addDrop(EntityGeneralGraardor.class, 1, new ItemStack(ScapecraftItems.magicFruit));
		addDrop(EntityGeneralGraardor.class, 100, new ItemStack(ScapecraftBlocks.mithOreSpawn));
		addDrop(EntityGeneralGraardor.class, 100, new ItemStack(ScapecraftItems.bandosHilt));
		addDrop(EntityGeneralGraardor.class, 100, new ItemStack(ScapecraftItems.dragonBoots));
		addDrop(EntityGeneralGraardor.class, 100, new ItemStack(ScapecraftItems.dragonHelmet));
		addDrop(EntityGeneralGraardor.class, 1000, new ItemStack(ScapecraftBlocks.runeOreSpawn));
		addDrop(EntityGeneralGraardor.class, 20, new ItemStack(ScapecraftItems.runegHelmet));
		addDrop(EntityGeneralGraardor.class, 200, new ItemStack(ScapecraftBlocks.addyOreSpawn));
		addDrop(EntityGeneralGraardor.class, 2000, new ItemStack(ScapecraftItems.crystalBow));
		addDrop(EntityGeneralGraardor.class, 3, new ItemStack(ScapecraftItems.mithChestplate));
		addDrop(EntityGeneralGraardor.class, 30, new ItemStack(ScapecraftItems.runegLeggings));
		addDrop(EntityGeneralGraardor.class, 4, new ItemStack(Items.gold_ingot));
		addDrop(EntityGeneralGraardor.class, 4, new ItemStack(ScapecraftBlocks.addyOre));
		addDrop(EntityGeneralGraardor.class, 4, new ItemStack(ScapecraftItems.addyChestplate));
		addDrop(EntityGeneralGraardor.class, 500, new ItemStack(ScapecraftBlocks.coalOreSpawn));
		addDrop(EntityGeneralGraardor.class, 75, new ItemStack(ScapecraftItems.bandosBoots));
		addDrop(EntityGeneralGraardor.class, 75, new ItemStack(ScapecraftItems.bandosChestplate));
		addDrop(EntityGhost.class, 100, new ItemStack(ScapecraftItems.addyChestplate));
		addDrop(EntityGhost.class, 130, new ItemStack(ScapecraftItems.runeHelmet));
		addDrop(EntityGhost.class, 2, new ItemStack(Items.gold_nugget));
		addDrop(EntityGhost.class, 20, new ItemStack(Blocks.obsidian));
		addDrop(EntityGhost.class, 2000, new ItemStack(ScapecraftItems.dragonLeggings));
		addDrop(EntityGhost.class, 30, new ItemStack(ScapecraftItems.blackChestplate));
		addDrop(EntityGhost.class, 30, new ItemStack(ScapecraftItems.mithBoots));
		addDrop(EntityGhost.class, 30, new ItemStack(ScapecraftItems.mithHelmet));
		addDrop(EntityGhost.class, 50, new ItemStack(ScapecraftItems.graniteLump));
		addDrop(EntityGhost.class, 55, new ItemStack(ScapecraftBlocks.addyOre));
		addDrop(EntityGhost.class, 700, new ItemStack(ScapecraftItems.dragonLongsword));
		addDrop(EntityGoblin.class, 100, new ItemStack(ScapecraftItems.magicFruit)); 
		addDrop(EntityGoblin.class, 15, new ItemStack(Items.wooden_sword));
		addDrop(EntityGoblin.class, 200, new ItemStack(ScapecraftItems.graniteLump));
		addDrop(EntityGoblin.class, 3000, new ItemStack(ScapecraftItems.runegBoots));
		addDrop(EntityGoblin.class, 30000, new ItemStack(ScapecraftItems.crystalBow)); 
		addDrop(EntityGoblin.class, 400, new ItemStack(ScapecraftItems.runeSword));
		addDrop(EntityGoblin.class, 6, new ItemStack(Items.gold_nugget));
		addDrop(EntityGreenDragon.class, 1, new ItemStack(ScapecraftItems.greenDHide));
		addDrop(EntityGreenDragon.class, 1000, new ItemStack(ScapecraftItems.dragonScimmy));
		addDrop(EntityGreenDragon.class, 1000, new ItemStack(ScapecraftItems.runeChestplate));
		addDrop(EntityGreenDragon.class, 1000, new ItemStack(ScapecraftItems.shard1));
		addDrop(EntityGreenDragon.class, 15, new ItemStack(ScapecraftItems.mithBoots));
		addDrop(EntityGreenDragon.class, 2000, new ItemStack(ScapecraftItems.armadylHilt));
		addDrop(EntityGreenDragon.class, 3, new ItemStack(Items.gold_ingot));
		addDrop(EntityGreenDragon.class, 5, new ItemStack(ScapecraftBlocks.addyOre));
		addDrop(EntityGreenDragon.class, 500000, new ItemStack(ScapecraftItems.dragonChestplate));
		addDrop(EntityGuard.class, 140, new ItemStack(ScapecraftItems.guardHelmet));
		addDrop(EntityGuard.class, 150, new ItemStack(Items.stone_sword));
		addDrop(EntityGuard.class, 160, new ItemStack(ScapecraftItems.guardChestplate));
		addDrop(EntityGuard.class, 5000, new ItemStack(ScapecraftItems.DD));
		addDrop(EntityGuthan.class, 1, new ItemStack(ScapecraftItems.guthanKey));
		addDrop(EntityGuthan.class, 300, new ItemStack(ScapecraftItems.guthanBoots));
		addDrop(EntityGuthan.class, 300, new ItemStack(ScapecraftItems.guthanChestplate));
		addDrop(EntityGuthan.class, 300, new ItemStack(ScapecraftItems.guthanHelmet));
		addDrop(EntityGuthan.class, 300, new ItemStack(ScapecraftItems.guthanLeggings));
		addDrop(EntityGuthan.class, 400, new ItemStack(ScapecraftItems.dragonLeggings));
		addDrop(EntityGuthan.class, 400, new ItemStack(ScapecraftItems.guthanSpear));
		addDrop(EntityHeroKnight.class, 14, new ItemStack(ScapecraftItems.whiteSword));
		addDrop(EntityHeroKnight.class, 15500, new ItemStack(ScapecraftItems.dragonLeggings));
		addDrop(EntityHeroKnight.class, 40, new ItemStack(ScapecraftItems.whiteBoots));
		addDrop(EntityHeroKnight.class, 40, new ItemStack(ScapecraftItems.whiteHelmet));
		addDrop(EntityHeroKnight.class, 60, new ItemStack(Items.gold_nugget, 2));
		addDrop(EntityHeroKnight.class, 60, new ItemStack(ScapecraftItems.whiteChestplate));
		addDrop(EntityHeroKnight.class, 60, new ItemStack(ScapecraftItems.whiteLeggings));
		addDrop(EntityHighMage.class, 1, new ItemStack(Items.gold_ingot, 4));
		addDrop(EntityHighMage.class, 100, new ItemStack(ScapecraftBlocks.mithOreSpawn));
		addDrop(EntityHighMage.class, 1000, new ItemStack(ScapecraftBlocks.runeOreSpawn));
		addDrop(EntityHighMage.class, 1500, new ItemStack(ScapecraftItems.armaStaff));
		addDrop(EntityHighMage.class, 2, new ItemStack(ScapecraftItems.saraStaff));
		addDrop(EntityHighMage.class, 20, new ItemStack(ScapecraftItems.dragonPickaxeg));
		addDrop(EntityHighMage.class, 200, new ItemStack(ScapecraftBlocks.addyOreSpawn));
		addDrop(EntityHighMage.class, 4, new ItemStack(Items.golden_apple));
		addDrop(EntityHighMage.class, 5, new ItemStack(ScapecraftItems.dragonLongsword));
		addDrop(EntityHighMage.class, 500, new ItemStack(ScapecraftBlocks.coalOreSpawn));
		addDrop(EntityHillGiant.class, 1, new ItemStack(Items.gold_nugget));
		addDrop(EntityHillGiant.class, 100, new ItemStack(ScapecraftItems.addyChestplate));
		addDrop(EntityHillGiant.class, 20, new ItemStack(Blocks.obsidian));
		addDrop(EntityHillGiant.class, 20, new ItemStack(ScapecraftBlocks.mithOre));
		addDrop(EntityHillGiant.class, 2000, new ItemStack(ScapecraftItems.dragonLeggings));
		addDrop(EntityHillGiant.class, 30, new ItemStack(ScapecraftItems.blackChestplate));
		addDrop(EntityHillGiant.class, 30, new ItemStack(ScapecraftItems.blackHelmet));
		addDrop(EntityHillGiant.class, 30, new ItemStack(ScapecraftItems.whiteBoots));
		addDrop(EntityHillGiant.class, 60, new ItemStack(ScapecraftItems.graniteLump));
		addDrop(EntityHillGiant.class, 70, new ItemStack(ScapecraftItems.runeBoots));
		addDrop(EntityHillGiant.class, 700, new ItemStack(ScapecraftItems.dragonLongsword));
		addDrop(EntityIceGiant.class, 1, new ItemStack(Items.snowball));
		addDrop(EntityIceGiant.class, 13, new ItemStack(ScapecraftItems.graniteLump));
		addDrop(EntityIceGiant.class, 30, new ItemStack(ScapecraftItems.blackHelmet));
		addDrop(EntityIceGiant.class, 40, new ItemStack(ScapecraftItems.runeBoots));
		addDrop(EntityIceGiant.class, 500, new ItemStack(ScapecraftItems.dragonLeggings));
		addDrop(EntityIceGiant.class, 60, new ItemStack(ScapecraftItems.addyChestplate));
		addDrop(EntityIceGiant.class, 60, new ItemStack(ScapecraftItems.mithLeggings));
		addDrop(EntityIceGiant.class, 700, new ItemStack(ScapecraftItems.dragonLongsword));
		addDrop(EntityIronDragon.class, 20, new ItemStack(Items.gold_ingot));
		addDrop(EntityIronDragon.class, 200, new ItemStack(ScapecraftItems.DD));
		addDrop(EntityIronDragon.class, 2000, new ItemStack(ScapecraftItems.shard2));
		addDrop(EntityIronDragon.class, 3, new ItemStack(Items.iron_sword));
		addDrop(EntityIronDragon.class, 5, new ItemStack(Items.iron_chestplate));
		addDrop(EntityIronDragon.class, 50, new ItemStack(ScapecraftItems.runeChestplate));
		addDrop(EntityIronDragon.class, 500, new ItemStack(ScapecraftItems.dragonLeggings));
		addDrop(EntityKK.class, 1, new ItemStack(Items.gold_ingot, 2));
		addDrop(EntityKK.class, 1, new ItemStack(ScapecraftBlocks.addyOre, 2));
		addDrop(EntityKK.class, 100, new ItemStack(ScapecraftItems.dryRapier));
		addDrop(EntityKK.class, 15, new ItemStack(ScapecraftItems.dragonAxe));
		addDrop(EntityKK.class, 15, new ItemStack(ScapecraftItems.dragonBoots));
		addDrop(EntityKK.class, 150, new ItemStack(ScapecraftItems.dryLong));
		addDrop(EntityKK.class, 20, new ItemStack(ScapecraftBlocks.sandSpawn));
		addDrop(EntityKK.class, 30, new ItemStack(ScapecraftItems.DDS));
		addDrop(EntityKK.class, 4, new ItemStack(ScapecraftItems.runeBoots));
		addDrop(EntityKK.class, 4, new ItemStack(ScapecraftItems.runeChestplate));
		addDrop(EntityKK.class, 4, new ItemStack(ScapecraftItems.runeHelmet));
		addDrop(EntityKK.class, 4, new ItemStack(ScapecraftItems.runeLeggings));
		addDrop(EntityKK.class, 50, new ItemStack(ScapecraftItems.dryMace));
		addDrop(EntityKKspawn.class, 1000, new ItemStack(ScapecraftItems.dragonLongsword));
		addDrop(EntityKKspawn.class, 30, new ItemStack(Items.coal));
		addDrop(EntityKKspawn.class, 3000, new ItemStack(ScapecraftItems.dragonPickaxe));
		addDrop(EntityKKspawn.class, 400, new ItemStack(ScapecraftItems.korasis));
		addDrop(EntityKQ.class, 1, new ItemStack(Items.gold_ingot, 2));
		addDrop(EntityKQ.class, 1, new ItemStack(ScapecraftBlocks.addyOre, 2));
		addDrop(EntityKQ.class, 10, new ItemStack(ScapecraftItems.dragonLongsword));
		addDrop(EntityKQ.class, 2, new ItemStack(ScapecraftItems.mithLeggings));
		addDrop(EntityKQ.class, 50, new ItemStack(ScapecraftItems.dragon2hSword));
		addDrop(EntityKQ.class, 50, new ItemStack(ScapecraftItems.crystalBow));
		addDrop(EntityKQ.class, 60, new ItemStack(ScapecraftItems.dragonChestplate));
		addDrop(EntityKQ2.class, 100, new ItemStack(Items.coal));
		addDrop(EntityKQ2.class, 4000, new ItemStack(ScapecraftItems.korasis));
		addDrop(EntityKQ2.class, 5500, new ItemStack(ScapecraftItems.dragonLongsword));
		addDrop(EntityKQ2.class, 8000, new ItemStack(ScapecraftItems.dragonPickaxe));
		addDrop(EntityKaril.class, 1, new ItemStack(ScapecraftItems.karilKey));
		addDrop(EntityKaril.class, 300, new ItemStack(ScapecraftItems.karilBoots));
		addDrop(EntityKaril.class, 300, new ItemStack(ScapecraftItems.karilChestplate));
		addDrop(EntityKaril.class, 300, new ItemStack(ScapecraftItems.karilHelmet));
		addDrop(EntityKaril.class, 300, new ItemStack(ScapecraftItems.karilLeggings));
		addDrop(EntityKaril.class, 400, new ItemStack(ScapecraftItems.karilBow));
		addDrop(EntityKaril.class, 400, new ItemStack(ScapecraftItems.dragonLeggings));
		addDrop(EntityKing.class, 1, new ItemStack(Items.gold_ingot));
		addDrop(EntityKing.class, 100, new ItemStack(ScapecraftItems.saraSword));
		addDrop(EntityKing.class, 14, new ItemStack(ScapecraftItems.runeSword));
		addDrop(EntityKing.class, 30, new ItemStack(ScapecraftItems.DD));
		addDrop(EntityKing.class, 4, new ItemStack(ScapecraftItems.whiteHelmet));
		addDrop(EntityKing.class, 6, new ItemStack(ScapecraftItems.whiteChestplate));
		addDrop(EntityKing.class, 60, new ItemStack(ScapecraftItems.runeLeggings));
		addDrop(EntityKingsGuard.class, 10, new ItemStack(ScapecraftItems.guardChestplate));
		addDrop(EntityKingsGuard.class, 10, new ItemStack(ScapecraftItems.guardHelmet));
		addDrop(EntityKingsGuard.class, 100, new ItemStack(Items.golden_sword));
		addDrop(EntityKingsGuard.class, 10000, new ItemStack(ScapecraftItems.saraSword));
		addDrop(EntityKos3.class, 1, new ItemStack(Items.gold_ingot, 2));
		addDrop(EntityKos3.class, 1, new ItemStack(ScapecraftBlocks.runeOre));
		addDrop(EntityKos3.class, 10, new ItemStack(ScapecraftItems.dragonHelmet));
		addDrop(EntityKos3.class, 100, new ItemStack(ScapecraftBlocks.coalOreSpawn));
		addDrop(EntityKos3.class, 100, new ItemStack(ScapecraftItems.crystalBow));
		addDrop(EntityKos3.class, 15, new ItemStack(ScapecraftBlocks.cabbageSpawn));
		addDrop(EntityKos3.class, 2, new ItemStack(ScapecraftItems.fremSword));
		addDrop(EntityKos3.class, 20, new ItemStack(ScapecraftItems.dragonLeggings));
		addDrop(EntityKos3.class, 200, new ItemStack(ScapecraftBlocks.runeOreSpawn));
		addDrop(EntityKos3.class, 3, new ItemStack(ScapecraftItems.mithChestplate));
		addDrop(EntityKos3.class, 30, new ItemStack(ScapecraftBlocks.mithOreSpawn));
		addDrop(EntityKos3.class, 30, new ItemStack(ScapecraftItems.runegBoots));
		addDrop(EntityKos3.class, 40, new ItemStack(ScapecraftBlocks.diamondOreSpawn));
		addDrop(EntityKos3.class, 50, new ItemStack(ScapecraftItems.fremSwordf));
		addDrop(EntityKos3.class, 60, new ItemStack(ScapecraftBlocks.addyOreSpawn));
		addDrop(EntityLesserDemon.class, 10, new ItemStack(ScapecraftBlocks.mithOre));
		addDrop(EntityLesserDemon.class, 1000, new ItemStack(ScapecraftItems.DBA));
		addDrop(EntityLesserDemon.class, 3000, new ItemStack(ScapecraftItems.chaoticRapier));
		addDrop(EntityLesserDemon.class, 5, new ItemStack(ScapecraftItems.mithHelmet));
		addDrop(EntityLesserDemon.class, 5, new ItemStack(ScapecraftItems.whiteChestplate));
		addDrop(EntityLesserDemon2.class, 10, new ItemStack(ScapecraftBlocks.mithOre));
		addDrop(EntityLesserDemon2.class, 1000, new ItemStack(ScapecraftItems.shard3));
		addDrop(EntityLesserDemon2.class, 1400, new ItemStack(ScapecraftItems.DBA));
		addDrop(EntityLesserDemon2.class, 4000, new ItemStack(ScapecraftItems.chaoticRapier));
		addDrop(EntityLesserDemon2.class, 5, new ItemStack(ScapecraftItems.mithHelmet));
		addDrop(EntityLesserDemon2.class, 5, new ItemStack(ScapecraftItems.whiteChestplate));
		addDrop(EntityLootChest.class, 1, new ItemStack(Items.gold_ingot));
		addDrop(EntityLootChest.class, 1, new ItemStack(Items.gold_ingot));
		addDrop(EntityLootChest.class, 1, new ItemStack(ScapecraftItems.questPoint3));
		addDrop(EntityLootChest.class, 1, new ItemStack(ScapecraftItems.fishPieUncooked, 10));
		addDrop(EntityLootChest.class, 1, new ItemStack(ScapecraftItems.whiteBoots));
		addDrop(EntityLootChest.class, 1, new ItemStack(ScapecraftItems.whiteChestplate));
		addDrop(EntityLootChest.class, 1, new ItemStack(ScapecraftItems.whiteHelmet));
		addDrop(EntityLootChest.class, 1, new ItemStack(ScapecraftItems.whiteLeggings));
		addDrop(EntityLootChest.class, 1, new ItemStack(ScapecraftItems.whiteSword));
		addDrop(EntityMan.class, 140, new ItemStack(ScapecraftItems.guardHelmet));
		addDrop(EntityMan.class, 150, new ItemStack(Items.stone_sword));
		addDrop(EntityMan.class, 160, new ItemStack(ScapecraftItems.guardChestplate));
		addDrop(EntityMan.class, 5000, new ItemStack(ScapecraftItems.DD));
		addDrop(EntityMan.class, 8, new ItemStack(Items.gold_nugget));
		addDrop(EntityMossGiant.class, 1, new ItemStack(Items.gold_nugget));
		addDrop(EntityMossGiant.class, 10, new ItemStack(Blocks.obsidian));
		addDrop(EntityMossGiant.class, 10, new ItemStack(ScapecraftBlocks.mithOre));
		addDrop(EntityMossGiant.class, 10, new ItemStack(ScapecraftItems.blackChestplate));
		addDrop(EntityMossGiant.class, 10, new ItemStack(ScapecraftItems.whiteBoots));
		addDrop(EntityMossGiant.class, 1300, new ItemStack(ScapecraftItems.dragonLeggings));
		addDrop(EntityMossGiant.class, 20, new ItemStack(ScapecraftItems.blackHelmet));
		addDrop(EntityMossGiant.class, 40, new ItemStack(ScapecraftItems.graniteLump));
		addDrop(EntityMossGiant.class, 50, new ItemStack(ScapecraftItems.addyChestplate));
		addDrop(EntityMossGiant.class, 50, new ItemStack(ScapecraftItems.runeBoots));
		addDrop(EntityMossGiant.class, 600, new ItemStack(ScapecraftItems.dragonLongsword));
		addDrop(EntityMugger.class, 100, new ItemStack(ScapecraftItems.blackLeggings));
		addDrop(EntityMugger.class, 15, new ItemStack(ScapecraftItems.mithAxe));
		addDrop(EntityMugger.class, 15, new ItemStack(ScapecraftItems.mithHammer));
		addDrop(EntityMugger.class, 15, new ItemStack(ScapecraftItems.mithSword));
		addDrop(EntityMugger.class, 2, new ItemStack(Items.gold_nugget));
		addDrop(EntityMugger.class, 30, new ItemStack(ScapecraftItems.magicFruit));
		addDrop(EntityMugger.class, 3000, new ItemStack(ScapecraftItems.dragonBoots));
		addDrop(EntityRat.class, 10, new ItemStack(Items.gold_nugget));
		addDrop(EntityRat.class, 30, new ItemStack(ScapecraftItems.guardHelmet));
		addDrop(EntityRat.class, 5, new ItemStack(Items.stone_sword));
		addDrop(EntityRat.class, 5000, new ItemStack(ScapecraftItems.DD));
		addDrop(EntityRatSmall.class, 10, new ItemStack(Items.stone_sword));
		addDrop(EntityRatSmall.class, 100, new ItemStack(ScapecraftItems.guardHelmet));
		addDrop(EntityRatSmall.class, 4, new ItemStack(ScapecraftItems.ratTail));
		addDrop(EntityRatSmall.class, 40, new ItemStack(Items.gold_nugget));
		addDrop(EntityScorpion.class, 100, new ItemStack(ScapecraftItems.blackChestplate));
		addDrop(EntityScorpion.class, 100, new ItemStack(ScapecraftBlocks.magicLog));
		addDrop(EntityScorpion.class, 15, new ItemStack(Items.iron_pickaxe));
		addDrop(EntityScorpion.class, 3000, new ItemStack(ScapecraftItems.dragonPickaxe));
		addDrop(EntitySergeantGrimspike.class, 100, new ItemStack(ScapecraftItems.magicFruit));
		addDrop(EntitySergeantGrimspike.class, 1000, new ItemStack(ScapecraftItems.shard1));
		addDrop(EntitySergeantGrimspike.class, 10000, new ItemStack(ScapecraftItems.crystalBow));
		addDrop(EntitySergeantGrimspike.class, 15, new ItemStack(Items.wooden_sword));
		addDrop(EntitySergeantGrimspike.class, 500, new ItemStack(ScapecraftItems.dragonBoots));
		addDrop(EntitySergeantSteelwill.class, 100, new ItemStack(ScapecraftItems.magicFruit));
		addDrop(EntitySergeantSteelwill.class, 1000, new ItemStack(ScapecraftItems.shard2));
		addDrop(EntitySergeantSteelwill.class, 10000, new ItemStack(ScapecraftItems.crystalBow));
		addDrop(EntitySergeantSteelwill.class, 15, new ItemStack(Items.wooden_sword));
		addDrop(EntitySergeantSteelwill.class, 500, new ItemStack(ScapecraftItems.dragonBoots));
		addDrop(EntitySergeantStrongstack.class, 100, new ItemStack(ScapecraftItems.magicFruit));
		addDrop(EntitySergeantStrongstack.class, 1000, new ItemStack(ScapecraftItems.shard3));
		addDrop(EntitySergeantStrongstack.class, 15, new ItemStack(Items.wooden_sword));
		addDrop(EntitySergeantStrongstack.class, 500, new ItemStack(ScapecraftItems.dragonBoots));
		addDrop(EntitySergeantStrongstack.class, 5000, new ItemStack(ScapecraftItems.crystalBow));
		addDrop(EntityTD.class, 1, new ItemStack(Items.gold_ingot, 2));
		addDrop(EntityTD.class, 1, new ItemStack(ScapecraftBlocks.runeOre));
		addDrop(EntityTD.class, 1, new ItemStack(ScapecraftItems.magicFruit));
		addDrop(EntityTD.class, 100, new ItemStack(ScapecraftBlocks.mithOreSpawn));
		addDrop(EntityTD.class, 100, new ItemStack(ScapecraftItems.DBA));
		addDrop(EntityTD.class, 100, new ItemStack(ScapecraftItems.dragonHelmet));
		addDrop(EntityTD.class, 1000, new ItemStack(ScapecraftBlocks.runeOreSpawn));
		addDrop(EntityTD.class, 200, new ItemStack(ScapecraftBlocks.addyOreSpawn));
		addDrop(EntityTD.class, 2000, new ItemStack(ScapecraftItems.crystalBow));
		addDrop(EntityTD.class, 3, new ItemStack(ScapecraftItems.mithChestplate));
		addDrop(EntityTD.class, 400, new ItemStack(ScapecraftItems.dragonlBoots));
		addDrop(EntityTD.class, 400, new ItemStack(ScapecraftItems.dragonlChestplate));
		addDrop(EntityTD.class, 400, new ItemStack(ScapecraftItems.dragonlHelmet));
		addDrop(EntityTD.class, 400, new ItemStack(ScapecraftItems.dragonlLeggings));
		addDrop(EntityTD.class, 500, new ItemStack(ScapecraftBlocks.coalOreSpawn));
		addDrop(EntityTheif.class, 100, new ItemStack(ScapecraftItems.blackLeggings));
		addDrop(EntityTheif.class, 30, new ItemStack(ScapecraftItems.magicFruit));
		addDrop(EntityTheif.class, 3000, new ItemStack(ScapecraftItems.dragonBoots));
		addDrop(EntityTheif.class, 7, new ItemStack(ScapecraftItems.blackSword));
		addDrop(EntityTorag.class, 1, new ItemStack(ScapecraftItems.toragKey));
		addDrop(EntityTorag.class, 300, new ItemStack(ScapecraftItems.toragBoots));
		addDrop(EntityTorag.class, 300, new ItemStack(ScapecraftItems.toragChestplate));
		addDrop(EntityTorag.class, 300, new ItemStack(ScapecraftItems.toragHelmet));
		addDrop(EntityTorag.class, 300, new ItemStack(ScapecraftItems.toragLeggings));
		addDrop(EntityTorag.class, 400, new ItemStack(ScapecraftItems.dragonLeggings));
		addDrop(EntityTorag.class, 400, new ItemStack(ScapecraftItems.toragHammer));
		addDrop(EntityVampire.class, 1, new ItemStack(Items.gold_ingot));
		addDrop(EntityVampire.class, 1, new ItemStack(ScapecraftItems.questPoint));
		addDrop(EntityVampire.class, 3, new ItemStack(ScapecraftItems.blackBoots));
		addDrop(EntityVampire.class, 3, new ItemStack(ScapecraftItems.blackChestplate));
		addDrop(EntityVampire.class, 3, new ItemStack(ScapecraftItems.blackHelmet));
		addDrop(EntityVampire.class, 3, new ItemStack(ScapecraftItems.blackLeggings));
		addDrop(EntityVampire.class, 3, new ItemStack(ScapecraftItems.blackSword));
		addDrop(EntityVerac.class, 1, new ItemStack(ScapecraftItems.veracKey));
		addDrop(EntityVerac.class, 300, new ItemStack(ScapecraftItems.veracBoots));
		addDrop(EntityVerac.class, 300, new ItemStack(ScapecraftItems.veracChestplate));
		addDrop(EntityVerac.class, 300, new ItemStack(ScapecraftItems.veracHelmet));
		addDrop(EntityVerac.class, 300, new ItemStack(ScapecraftItems.veracLeggings));
		addDrop(EntityVerac.class, 400, new ItemStack(ScapecraftItems.dragonLeggings));
		addDrop(EntityVerac.class, 400, new ItemStack(ScapecraftItems.veracFlail));
		addDrop(EntityWhiteKnight.class, 140, new ItemStack(ScapecraftItems.whiteBoots));
		addDrop(EntityWhiteKnight.class, 140, new ItemStack(ScapecraftItems.whiteHelmet));
		addDrop(EntityWhiteKnight.class, 141, new ItemStack(ScapecraftItems.whiteSword));
		addDrop(EntityWhiteKnight.class, 160, new ItemStack(ScapecraftItems.whiteChestplate));
		addDrop(EntityWhiteKnight.class, 160, new ItemStack(ScapecraftItems.whiteLeggings));
		addDrop(EntityWhiteKnight.class, 3500, new ItemStack(ScapecraftItems.dragonLeggings));
		addDrop(EntityWizard.class, 1000, new ItemStack(ScapecraftItems.guthixStaff));
		addDrop(EntityWizard.class, 1000, new ItemStack(ScapecraftItems.saraStaff));
		addDrop(EntityWizard.class, 5000, new ItemStack(ScapecraftItems.saradominHilt));
		addDrop(EntityWizard.class, 8, new ItemStack(ScapecraftItems.barrowsTab));
		addDrop(EntityWizard.class, 8, new ItemStack(ScapecraftItems.bandosTab));
		addDrop(EntityWizard.class, 8, new ItemStack(ScapecraftItems.cathTab));
		addDrop(EntityWizard.class, 8, new ItemStack(ScapecraftItems.faladorTab));
		addDrop(EntityWizard.class, 8, new ItemStack(ScapecraftItems.hubTab));
		addDrop(EntityWizard.class, 8, new ItemStack(ScapecraftItems.lumbridgeTab));
		addDrop(EntityWizard.class, 8, new ItemStack(ScapecraftItems.tormentedDemonsTab));
		addDrop(EntityWizard.class, 8, new ItemStack(ScapecraftItems.varrockTeletab));
	}
}
